### ISSUE TITLE
Update the module design

### ISSUE THREAD

**Issue by portlek** [lokka30/Treasury#100]
### User Story

The design of modules can be improved by moving the platform-related modules into a separate `platform` module.

### Describe the solution you'd like.

Move the platform-related modules into a module called `platform` or `platforms`.

### Describe alternatives you've considered.

the way it looking can be like this:
- api
- core
- platform
  - bukkit
    - plugin
    - api
  - sponge
    - plugin
    - api
  - forge
    - mod
    - api
  - nukkit
    - plugin
    - api

artifact ids:
- treasury-api
- treasury-core
- treasury-platform
  - treasury-bukkit
    - treasury-bukkit-plugin
    - treasury-bukkit-api
  - treasury-sponge
    - treasury-sponge-plugin
    - treasury-sponge-api
  - treasury-forge
    - treasury-forge-mod
    - treasury-forge-api
  - treasury-nukkit
    - treasury-nukkit-plugin
    - treasury-nukkit-api

**Comment by MrNemo64** [comment]
I do like the idea

**Comment by lokka30** [comment]
I think this is a clearer layout +1

Would like to hear from @MrIvanPlays @Jikoo if possible :)

Thanks for submitting this suggestion!

**Comment by MrIvanPlays** [comment]
Uhh modules inside modules inside modules is not a very good idea. Once tried it and got messy quick. https://github.com/MrIvanPlays/Skins if you are interested in taking a look.

**Comment by Jikoo** [comment]
You don't have to have modules inside modules for this design. See https://github.com/Jikoo/OpenInv - module name is internal/v1_17_R1 etc. when referenced in parent.

👍 from me

**Comment by portlek** [comment]
@Jikoo i guess the only diff. is internal has not pom.xml file. if that's it, i think there is no diff at all on looking.
@MrIvanPlays putting all platforms in the root directory is not very good and looks messy too. but at least my design has some logic behind it, you can expect which module where.

**Comment by lokka30** [comment]
I think the nested modules seem more logical

**Comment by MrIvanPlays** [comment]
will wait on #102 before working on this.
