### ISSUE TITLE
Add 'Mob Owner' API

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#104]
### User Story

Being the author of LevelledMobs, I am consistently trying to maintain compatibility with other mob-modification plugins such as MythicMobs, EliteMobs and InfernalMobs, even boss plugins such as EcoBosses. I'll call these plugins (including LevelledMobs) 'mob owners', since they take control over mobs on the server.

Having a central API that allows all mob owners to hook into makes it far easier for all of the mob owner plugins to cooperate. Not only is there less code required to maintain compatibility, but there is also less dependencies and less worry and frustration when a mob owner plugin changes their API (which can happen all to frequently).

### Describe the solution you'd like.

On `EntitySpawnEvent`, I would like to easily check if an `Entity` is 'registered'/'reserved' by a mob owner plugin.

For example, LevelledMobs' EntitySpawnEvent listener could detect a zombie has spawned in the wilderness. First, LevelledMobs will contact Treasury to see if the mob has already been reserved by another mob. If configured to ignore mobs already registered by other mob owners, it will not level the mob. If the mob was not registered by any other mob owner, then LevelledMobs will level it and register it as the mob owner of the zombie.

### Describe alternatives you've considered.

The API is not required as each mob owner plugin can be hooked into individually of course. But having this API could simplify compatibility and ease of maintenance for all mob owner plugins which are interested.

### Additional information

It will be difficult to have all plugins cooperate on `EntitySpawnEvent` since the order in which mob owners process this event is different.

For example, LevelledMobs likes to operate on the `HIGH` priority since we often *provide* the compatibility, rarely *receive*, also because LevelledMobs acts as a 'default' mob owner of sorts since it operates on all mobs that spawn naturally. I believe that EliteMobs and InfernalMobs also operate on naturally spawned mobs, but LM likes to give them priority. This means we need to wait for most of the other mob owners to register their interest first.

Perhaps the API could have a `load-after` and `load-before` setting so a plugin can ensure other plugins register a mob prior to processing it.

**Comment by lokka30** [comment]
Tagging users who may be interested: @Jikoo @MrIvanPlays @MrNemo64

**Comment by MrIvanPlays** [comment]
Who except you and these plugins will use that API?

**Comment by lokka30** [comment]
> Who except you and these plugins will use that API?

Only boss, mobs and NPC plugins to provide compatibility with each other.

Do you think this should be a separate lib, outside of Treasury?

**Comment by MrIvanPlays** [comment]
I don't think this shall be in treasury's scope.

**Comment by lokka30** [comment]
> I don't think this shall be in treasury's scope.

I agree, the usage is too limited.

**Comment by MrNemo64** [comment]
Since this problem is kinda like logging your mob and a logging API for blocks was already mentioned, it could be there although is specific enough to make it hard to do
