### ISSUE TITLE
Add custom charts to the bStats page

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#116]
### Why add custom charts?
We should add some custom charts in for our bStats page. These additional metrics may assist us in guiding development towards where it would benefit most users.

### What are the current ideas?
- [x] `Simple Pie` the server's economy provider name (`String`, null = `None`)
- [x] `Simple Pie` If the economy provider supports negative balances (`boolean`)
- [x] `Simple Pie` If the economy provider supports transaction events (`boolean`)
- [x] `Bar Chart` API version of the Treasury version installed (`String`)
- [x] `Bar Chart` API version of the economy provider installed (`String`)
- [x] `Simple Pie` Has update checking enabled (`boolean`)
- [x] `Simple Pie` Amount of currencies (`int` - individual values from `0` to `9`, and then `10+`)

**Comment by MrIvanPlays** [comment]
We already have bstats implemented. We should just create the custom charts.

**Comment by lokka30** [comment]
Ahh cool, I thought we hadn't. Thanks for the heads up
