### ISSUE TITLE
Fix & regenerate javadocs before release

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#126]
See the comment [here](https://github.com/lokka30/Treasury/issues/5#issuecomment-1021847011) for more information.

**Comment by MrIvanPlays** [comment]
I will be able to fix it later.

**Comment by MrIvanPlays** [comment]
Done. We're just building them with java 17 now and stuff fixed automatically.

**Comment by MrNemo64** [comment]
> Done. We're just building them with java 17 now and stuff fixed automatically. 

Awesome
