### ISSUE TITLE
Unified subscriber response object

### ISSUE THREAD

**Issue by MrIvanPlays** [lokka30/Treasury#133]
We have the `EconomySubscriber`, let's evolve this to a `Subscriber<R, E>` so we can have something unified for the other APIs, not just for the economy api

**Comment by MrIvanPlays** [comment]
@Jikoo @lokka30

**Comment by lokka30** [comment]
I think unifying the subscribers is a good idea.

**Comment by Jikoo** [comment]
Agreed, though now that we're released we should keep the EconomySubscriber around so as not to cause a breaking change.

**Comment by lokka30** [comment]
> Agreed, though now that we're released we should keep the EconomySubscriber around so as not to cause a breaking change.

I think we might have to, but better to make the breaking change now than later. Otherwise the APIs will not be consistent. Hopefully we can make any other breaking changes at the same time.

**Comment by MrNemo64** [comment]
We could just make the subscriber an interface and implement it on the other APIs. We won't break what we have that way

**Comment by MrIvanPlays** [comment]
We can deprecate the economy subscriber just like what I plan to do with the events. I will be able to work on stuff again on 6th February.

**Comment by lokka30** [comment]
> We could just make the subscriber an interface and implement it on the other APIs. We won't break what we have that way

It would be weird to have the other APIs have subscribers that inherit an interface's name starting with `Economy` :)

**Comment by MrNemo64** [comment]
> It would be weird to have the other APIs have subscribers that inherit an interface's name starting with Economy :)

We make the `Subscriber<>` interface and push to it all the common methods across all the APIs, then we make the `EconomySubscriber<>` and all the other subscribers from other APIs implement it

**Comment by Geolykt** [comment]
Breaking ABI now would shed the wrong light on the project. It is already too late

**Comment by lokka30** [comment]
> > It would be weird to have the other APIs have subscribers that inherit an interface's name starting with Economy :)
> 
> We make the `Subscriber<>` interface and push to it all the common methods across all the APIs, then we make the `EconomySubscriber<>` and all the other subscribers from other APIs implement it

Perfect.



> Breaking ABI now would shed the wrong light on the project. It is already too late

Upon reflection, I completely agree.

**Comment by yannicklamprecht** [comment]
I wouldn't say that it will break. I'll craft a pr together. We just let inherit economy subscriber from that subscriber interface.
The methods from the economy subscriber interface are generic enough. At least what it looks like on mobile.

**Comment by MrIvanPlays** [comment]
What im thinking too is a unified treasury exception or something like that. @yannicklamprecht go with it. Im pretty sure you will make it right the first time.
