### ISSUE TITLE
Unified API version

### ISSUE THREAD

**Issue by MrIvanPlays** [lokka30/Treasury#134]
We have the EconomyAPIVersion, this should basically evolve into APIVersion in my opinion.

**Comment by MrIvanPlays** [comment]
@Jikoo @lokka30

**Comment by lokka30** [comment]
I disagree (not firmly). Say we make a change to the economy API, suddenly, you could think your permissions plugin is using the outdated permissions API. I think having independent versions for each API is a good idea.
