### ISSUE TITLE
Default implement Account#setName for player accounts

### ISSUE THREAD

**Issue by MrIvanPlays** [lokka30/Treasury#136]
Took a look at an economy provider and found out that this is not how it should be. We need a default implementation for this.

**Comment by MrNemo64** [comment]
How should this be? What would the default name be?

**Comment by MrIvanPlays** [comment]
**PlayerAccount#setName** 

you can't set a player account's name, can't you?

**Comment by MrNemo64** [comment]
Why wouldn't you?

**Comment by MrIvanPlays** [comment]
> Why wouldn't you?

It's a **player** account. A **player** account

**Comment by MrNemo64** [comment]
So what, you may still want to change the name. Can't we just left to the provider the decition of whether you should or should not be able to change the name of a player account?

**Comment by MrIvanPlays** [comment]
So you're claiming that I am able to change the name of a player? 

Default implementing the method does not mean the economy provider can't override it. They can.

**Comment by MrNemo64** [comment]
> So you're claiming that I am able to change the name of a player?

You wouldn't be changing the name of the player, rather the name of their account which may be the same as the player name or "MrIvanPlays' account" or who knows? We never specify that the name of a player account should match the name of the owner

**Comment by lokka30** [comment]
You're right. You can't set a name of a player account because their username can change. Therefore player accounts should default to having no name.

**Comment by MrIvanPlays** [comment]
Afaik getName is being implemented as the name of the player and setName is being implemented as calling subscriber.succeed(false). So we need that default implementation of setName and if the economy provider wishes to change that they can override.

**Comment by lokka30** [comment]
> Afaik getName is being implemented as the name of the player and setName is being implemented as calling subscriber.succeed(false). So we need that default implementation of setName and if the economy provider wishes to change that they can override.

Sounds good to e.

**Comment by lokka30** [comment]
I don't think we can provide a default for `getName` but definitely `setName` to succeed `false`.
