### ISSUE TITLE
Work on a Chat API

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#14]
I'd like to implement a Chat API into Treasury.

I'm very interested in what anyone has to say about this, since this is the perfect opportunity to create a great Chat API.

I'm unsure when this will be added, and the Economy API is heavily prioritized over this.

**Comment by lokka30** [comment]
Note: the `developer thoughts wanted` label requests any ideas from developers regarding this API. What should people expect from a new Chat API? What do existing Chat APIs do incorrectly?

**Comment by MrNemo64** [comment]
I've been thinking about this and this is what I came with:
1. Maybe making this a provider-consumer system isn't a great idea, how many chat providers are there?
2. Multi lang support: I would like to be able to tell to the chat API where my lang files are and the API will manage them, for example:
```Java
TreasuryChat chatAPI = ...
Plugin myPlugin = ...
File myLangFolder = ... // where all my lang files are
String defaultLangFile = "en_US.yml" // default lang file to use
chatAPI.registerLangFolder(myPlugin , myLangFolder, defaultLangFile );
```
Now that the API knows where my lang files are I would be able to do the following:
```Java
TreasuryChat chatAPI = ...
Player player = ...
Plugin myPlugin = ...
Map<String, String> variables = ... // variables of the message
chatAPI.sendMessage(myPlugin, player, "messages.welcome", variables);
```
Now the chat API will do the following:
  1. Get the language of the player (maybe a player can specify its language with a command or maybe using [`Player#getLocate()`](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/Player.html#getLocale()))
  2. The chat API will check if there is a lang file in my lang folder with the same language as the players
    - If the lang file is found and it has the message, uses that message
    - If the lang file isn't found/doesn't have the entry, the default lang file is used
    - If the message is still not found throw a RuntimeException
  3. The chat API colors, replaces variables, etc and sends the message
 
I've seen that some chat plugins allow for chat channels so you join a channel and only recieve messages sent on that channel. Don't know if this is worth doing.
Maybe the API should allow to make messages with click and hover events
Maybe a mails/memory system should be done: being able to send a message to a player even if its offline. When the player joins all those messages are sent/they are told that they have messages to read (kinda like essentials mail system)

This is what I thought so far

**Comment by lokka30** [comment]
Thank you very much for noting your thoughts @MrNemo64 - I haven't yet taken a look into what a Chat API should offer (e.g. by comparing existing ones). Might be able to sort this out once the economy API is done, but still definitely looking for thoughts on this idea.

**Comment by yannicklamprecht** [comment]
Out of the box Adventure Component and MiniMessage support would be a welcome feature.

**Comment by lokka30** [comment]
> Out of the box Adventure Component and MiniMessage support would be a welcome feature.

Would you consider MineDown being part of your welcomed features list?

**Comment by yannicklamprecht** [comment]
> > Out of the box Adventure Component and MiniMessage support would be a welcome feature.
> 
> Would you consider MineDown being part of your welcomed features list?

Does it support more Maroden features that the one supported by MM? https://docs.adventure.kyori.net/minimessage#markdown-flavors

**Comment by lokka30** [comment]
> > > Out of the box Adventure Component and MiniMessage support would be a welcome feature.
> > 
> > 
> > Would you consider MineDown being part of your welcomed features list?
> 
> Does it support more Markdown features than the one supported by MM? https://docs.adventure.kyori.net/minimessage#markdown-flavors

Plenty: https://github.com/Phoenix616/MineDown
:smiley:

**Comment by lokka30** [comment]
Closing this issue until we get to implementing it. See the [discussion](https://github.com/lokka30/Treasury/discussions/128) for new APIs if you would like to chat about this idea.
