### ISSUE TITLE
Have separate API versions for each individual API in Treasury

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#140]
Current Solution:

> what i just got in mind is to as we agreed on ditch the api version, but also expose the plugin version. we already have an object for it in the core module, we can just move that to the API and make a way of retrieving it.

***

Each API within Treasury needs its own API version.

~~⚠️ There is one issue I don't know how to solve yet:~~
* ~~What do we do about changes to the common package? E.g., #138 would be such. How do we version this? Should the common package have its own API version, and/or, should any change to the common package which affects an API make the versions of each API affected be increased?~~

The reason all APIs should not use a single version for all to share, is because one change in the economy API means suddenly all permissions plugins think they're running an outdated version of the permissions API.

This is required to solve #138.

I will work on this unless anyone else prefers to.

Any feedback/ideas on this, feel free to leave it below :smiley:

Tagging those who may be interested: @yannicklamprecht @MrIvanPlays @Jikoo @MrNemo64

**Comment by lokka30** [comment]
How I would implement this:
* Keep EconomyAPIVersion the exact same. each API will have the same system but they are not linked by any interface or something. Just a plain enum, as-is. For example, PermissionsAPIVersion would have the same code, just different constants (versions).
* Any change to the `api.common` package will affect the version of each API which utilizes it. For example, #138 will increment the version of *every* API because the subscriber will be used in every API (which I am aware of). Of course we currently only have the economy API anyways.
  * **HOWEVER**, since the economy API is not actually affected by this change for anyone who implements Treasury (the economy subscriber still exists completely normal), the API version won't change. This is probably controversial, I'm not sure about this.

**Comment by MrNemo64** [comment]
A change to the common package means an increment on every API if the change is not a patch

Since the #138 is a code quality change that doesn't really afect anything it should be treated as a patch so we wouldn't increment API versions

**Comment by lokka30** [comment]
> A change to the common package means an increment on every API if the change is not a patch
> 
> Since the #138 is a code quality change that doesn't really afect anything it should be treated as a patch so we wouldn't increment API versions

Sounds great to me. Thanks for the feedback :smiley:

**Comment by MrIvanPlays** [comment]
in that case we need a common api version. that's why i suggested we have 1 unified api version but that got rejected for a fair reason. 

solution here is to ditch the api version concept in the code itself. im gonna back this as the argument that we have maven and plugin versioning.

**Comment by lokka30** [comment]
I think the versioning system Nemo and I've got in mind is pretty solid, of course not perfect. It's easy for implementers to understand and easy for us to use.

* breaking changes -> increase major version
* additions/fixes -> increase minor version
* any changes to the common package -> increase version of all affected APIs e.g. economy
* all methods have a link to state what API version they were implemented at
* all service providers state what API version they are developing against so any possible incompatibility is clear from the beginning

**Comment by lokka30** [comment]
> > any changes to the common package -> increase version of all affected APIs e.g. economy
> 
> i suggest to ditch the entire api version scenario from the code.

I think it would be overall quite detrimental to do so. Otherwise, we can remove the API versions and hold back our development to make sure the APIs are as stable as possible, but then we'll get nowhere.

**Comment by Jikoo** [comment]
> > any changes to the common package -> increase version of all affected APIs e.g. economy
> 
> that's what i don't agree with. that's why i mentioned common api version. but then we get a lot of api versions. that's why i suggest to ditch the entire api version scenario from the code.

I think of it more like shaded dependencies you're distributing - if something you're shading is intended to be used by dependencies, you should treat version increments to it the same way you would treat version increments to your own code. A breaking change yielding a major version bump should be a major version bump whether the change is in the module or one it depends on.

Imo the important thing here is that just because something is added to the common module does not mean we instantly need to draft a new release of every single dependent module. If the new feature is only useful in 2/5 dependencies, only those 2 would need to update the version of the common module used immediately and draft a new release.

That all said, I'm now envisioning someone working with Treasury Economy 1.2 and Treasury Permissions 1.3 and one having Treasury Common 1.1 and the other Treasury Common 1.2. Kind of a mess to interact with, I'm pretty sure it'd be a toss-up which the Bukkit classloader provided. Technically they'd be able to check the common API version if we provide that, but without it it's a shot in the dark.

**Comment by lokka30** [comment]
> > > any changes to the common package -> increase version of all affected APIs e.g. economy
> > 
> > 
> > that's what i don't agree with. that's why i mentioned common api version. but then we get a lot of api versions. that's why i suggest to ditch the entire api version scenario from the code.
> 
> I think of it more like shaded dependencies you're distributing - if something you're shading is intended to be used by dependencies, you should treat version increments to it the same way you would treat version increments to your own code. A breaking change yielding a major version bump should be a major version bump whether the change is in the module or one it depends on.
> 
> Imo the important thing here is that just because something is added to the common module does not mean we instantly need to draft a new release of every single dependent module. If the new feature is only useful in 2/5 dependencies, only those 2 would need to update the version of the common module used immediately and draft a new release.
> 
> That all said, I'm now envisioning someone working with Treasury Economy 1.2 and Treasury Permissions 1.3 and one having Treasury Common 1.1 and the other Treasury Common 1.2. Kind of a mess to interact with, I'm pretty sure it'd be a toss-up which the Bukkit classloader provided. Technically they'd be able to check the common API version if we provide that, but without it it's a shot in the dark.

Nemo and I think that there should be no common package version, rather, any APIs affected by changes to the common package will result in increments to such APIs. Do you like this system? Else, do you have any alternatives in mind?

**Comment by MrIvanPlays** [comment]
another issue that came up in my mind is the update checking. it will be a really tedious process to check treasury common, treasury economy, treasury permission, treasury whatever api version, probs resulting in a spaghetti code. also, how would we know the common api version for a provider? there are lots of caveats in this api version system. im all for ditching. prove me wrong

**Comment by lokka30** [comment]
Agreed. Plugin version annotation will suffice.

**Comment by MrIvanPlays** [comment]
ye exactly we can just have 1 version why complicate stuff

**Comment by lokka30** [comment]
We'll get @Jikoo's approval for this if he agrees

**Comment by Jikoo** [comment]
Yeah, I think a unified version is best.

> Nemo and I think that there should be no common package version, rather, any APIs affected by changes to the common package will result in increments to such APIs. Do you like this system? Else, do you have any alternatives in mind?

This was my initial stance, but having thought about it I believe a bump to common needs a new release for everything providing common. It's a touch more nuisance for server administrators, but it improves quality of life for developers tremendously.

Honestly if that's the case, should Treasury just bundle all of its APIs into one uberjar for distribution? I can't imagine adding maybe 10-20 additional classes would yield a prohibitive filesize. It fixes the versioning issues, reduces the server admin load, and keeps things simple on the development end.

**Comment by MrIvanPlays** [comment]
treasury already bundles all of its apis into one jar. except platform specific apis obv

**Comment by Jikoo** [comment]
Well, Treasury doesn't yet have additional APIs to offer, there's only the economy. If all we ever plan to distribute is an uberjar there's very little reason to have separate API versions, yeah. Support single unified version 👍

**Comment by Jikoo** [comment]
I like the idea of having it so that providers don't have to do parsing work to figure out what's supported, but I think that should largely be a thing that the providers handle rather than Treasury doing it for them - it's not our job to police implementations. As long as Treasury's versioning is consistent it shouldn't be a problem either way. I don't dislike deleting it as a result, but I don't mind keeping it around.

**Comment by lokka30** [comment]
I think the current solution is to just remove the API version entirely (of course deprecate it for a few weeks or so before it is removed). Does anyone disagree?

**Comment by MrIvanPlays** [comment]
what i just got in mind is to as we agreed on ditch the api version, but also expose the plugin version. we already have an object for it in the core module, we can just move that to the API and make a way of retrieving it.
