### ISSUE TITLE
Service API Improvements

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#149]
I have some ideas which I think will improve the Service API. Please leave any honest feedback down below.

## 1. Clear up the definitions
- [ ] Resolved?

### Current definitions:
* A `Service` is a class that represents a registration for a class by a plugin.
* The `ServiceProvider` is where service registrations are handled.

This does not fit the original terminology we used.

### I propose:
* A `ServiceProvider` is a plugin's class that registers for a `Service`, e.g., BetterEconomy's Treasury economy hook.
* A `Service` is any class which can be registered for, i.e. the `EconomyProvider`.
* A `ServiceRegistration` is a class that represents a registration for a class by a plugin.
* The `ServiceHandler` is where Treasury allows plugins to register and unregister a `Service`.

### What remains the same:
Everything else ... `ServicePriority`, `registrarName`, etc.

***

## 2. Add a `void unregister()` method on each `Service` / `ServiceRegistration`
- [x] Resolved? **Cancelled**

<details>
<summary>View anyways</summary>

This can help to unregister an individual `Service` from its class which may be more convenient than using the `ServiceProvider` to do so.

</details>

***

## 3. Add automatic service unregistration on plugin disables
- [x] Resolved? **Cancelled**

<details>
<summary>View anyways</summary>

When a plugin is registering a service, and the plugin gets disabled, then the plugin should automatically un-register from that service.
When a plugin is providing a service, and that plugin is disabled, then all plugins registering to that service should automatically un-register from that service.

</details>

***

## 4. Renaming Events
- [x] Resolved? **Cancelled.**

<details>
<summary>View anyways</summary>

I believe we should remove the `ed` characters from the event names:
* `ServiceRegisteredEvent` -> `ServiceRegisterEvent`
* `ServiceUnregisteredEvent` -> `ServiceUnregisterEvent`

`ed` implies it has happened, rather than without `ed` implies it intends to happen but is interruptible. 

</details>

**Comment by lokka30** [comment]
@MrIvanPlays how much of this is already implemented? If any of them are missing and also desired, then would you like me to work on this?

**Comment by MrIvanPlays** [comment]
Services can be unregistered. Event subscriptions cannot and i am strongly against implementing a way of unregistering. In running circumstances a plugin shall never get shut down. If the plugin is erroring on startup the author of the plugin shall fix it. We in no way shall be responsible of cleaning up the shit someone else created.

**Comment by lokka30** [comment]
Merging to a new issue

**Comment by lokka30** [comment]
Hi @MrIvanPlays @Jikoo @yannicklamprecht @MrNemo64. If you are able to review my ideas then that would be appreciated.

**Comment by MrIvanPlays** [comment]
Also no renaming of classes. ServiceProvider is where stuff is registered. No weird ServiceHandler shit

**Comment by lokka30** [comment]
> I only agree about the better documentation. Nothing else

Not once have I mentioned documentation

**Comment by MrIvanPlays** [comment]
You're overcomplicating things. I like stuff which are simple. Ever seen luckperms' api? Lucko did fix some stuff in v5 but v4 was a complete utter shit. I want to get the prefix of a user, I have to get a user instance, get a ton other shit and then I might or might not get a prefix, because of a ton complications and features. 
Sure, not having features is a problem, but having too much features is also a problem, and one way to describe this is overcomplicating and featurebloat.

**Comment by MrIvanPlays** [comment]
Languages such as yaml and toml struggle because they have too many features. Ever seen what snakeyaml's code looks like? Their parser and their dumper is complete spaghetti because of that. It's the same in annotationconfig where I created my own yaml dumper because snakeyaml's dumper didn't support comments ( now it does but its a buggy system ) and didn't suit the needs of annotationconfig

**Comment by lokka30** [comment]
I apologize, I am unsure what you are referencing here, regarding the overcomplication / too much features. I completely agree with your argument that overcomplication is bad although I don't know what you're trying to point that towards :)

**Comment by MrIvanPlays** [comment]
Im trying to point that I don't want any of treasury's apis nor implementation code to become spaghetti or hard to use.

**Comment by MrIvanPlays** [comment]
The events in that case are purely for informative purposes, no one shall be able to stop someone from (un)registering a service. Against implementing cancellable. 

Im not going to participate in the conversation any further until tomorrow because I can't clearly see the asked changes although I have a understanding of what you want to do

**Comment by lokka30** [comment]
> The events in that case are purely for informative purposes, no one shall be able to stop someone from (un)registering a service. Against implementing cancellable.
> 
> Im not going to participate in the conversation any further until tomorrow because I can't clearly see the asked changes although I have a understanding of what you want to do

I apologize, I wrongly assumed these events were cancellable. I'll strikethrough point 4.

**Comment by MrIvanPlays** [comment]
Re: unregister method ; if we're gonna be convenient then lets implement the vault api so that people won't need to install vault but treasury. No

**Comment by MrIvanPlays** [comment]
Re: definitions ; the last 2 are unnecessary.

**Comment by lokka30** [comment]
> Re: unregister method ; if we're gonna be convenient then lets implement the vault api so that people won't need to install vault but treasury. No

implementing Vault is a polar opposite comparison towards adding a simple method to the service class to make unregistration simpler.


> Re: definitions ; the last 2 are unnecessary.

it's either the current definitions or the ones I propose, there's no inbetween - although of course we can edit the proposed ones if we do desire to remove the current definitions.

> Re: automatic unregistration on plugin disable ; there is no way only a individual plugin to get disabled. Either way as I previously said in another issue or discord, we shouldn't be responsible for cleaning up the shit someone else created.

Agreed, we should let people do their job properly.

**Comment by lokka30** [comment]
My ideas come as soon as they are generated. I do not delay them. Better now than ***after*** we release it.

Okay, scratch the idea for the unregister method then.

**Comment by MrNemo64** [comment]
I have nothing to add here

**Comment by MrIvanPlays** [comment]
we shall stop using the "plugin" term because treasury's api is not bound to any platform.

**Comment by lokka30** [comment]
Let's not close the v1.1 project until Jikoo says yes/no/idk for this and #147

**Comment by MrIvanPlays** [comment]
@Jikoo

**Comment by Jikoo** [comment]
Okay, going to ignore entries already marked resolved.

Re: terminology: 

> * A `ServiceProvider` is a plugin's class that registers for a `Service`, e.g., BetterEconomy's Treasury economy hook.
> * A `Service` is any class which can be registered for, i.e. the `EconomyProvider`.
> * A ServiceRegistration is a class that represents a registration for a class by a plugin.

Frankly, this seems redundant. If they can just register a `Service`, why should we make them also write a `ServiceProvider` to wrap `Service` instantiation? If the `ServiceRegistration` is just a wrapper for a `Service` registration, having a method to determine a `Service`'s registrar (as the provider should always be the registrar anyway) instead of adding layers of navigational complexity seems way better. No to this segment from me.

> *The ServiceHandler is where Treasury allows plugins to register and unregister a Service.

Generally what currently is named `ServiceProvider` is named `ServiceManager` or something similar because it manages services, it doesn't provide the implementations. Relatively ambivalent on this. I wouldn't mind a slightly more clarified name but I also see the existing one as valid, it still does provide services to the requesting API users.

**Comment by MrIvanPlays** [comment]
so we're not changing anything? am i correct

**Comment by lokka30** [comment]
I would also like to rename `ServiceProvider` -> `ServiceManager`. @MrIvanPlays do you agree?

**Comment by MrIvanPlays** [comment]
I didn't name it ServiceManager because I wanted to distance from bukkit. What's wrong with ServiceProvider? We have the Service class, basically the ServiceProvider provides Service.

**Comment by lokka30** [comment]
> I didn't name it ServiceManager because I wanted to distance from bukkit. What's wrong with ServiceProvider? We have the Service class, basically the ServiceProvider provides Service.

Would be `ServiceHandler` be a viable replacement then? I just don't believe `Provider` sounds as good. I agree to not use `Manager`, you're right that we should keep a clear distance from Bukkit. But I really don't mind how this turns out, just trying to improve things so long you guys agree.

**Comment by MrIvanPlays** [comment]
no. you're not handling services, are you? you're providing them, hence ServiceProvider.

**Comment by lokka30** [comment]
> no. you're not handling services, are you? you're providing them, hence ServiceProvider.

The terminology `provider` and `consumer` is already used in the 'provider and consumer' model we describe Treasury integrations by. There is ought to be a better term we can use.

I still think `Handler` is alright, because "the class **handles** the registration of services".

**Comment by MrIvanPlays** [comment]
okay i didn't want to pull out this card, but i'll have to.

stop being a woman. what does a woman do? she says "body doesn't matter" yet she wants the boy to be atleast 1.8 m tall. what i mean by that is if you're fine with that name, then stop wasting others (and yours) time.

**Comment by lokka30** [comment]
If you're going to reply, at least make it contribute to the conversation.

**Comment by MrNemo64** [comment]
> okay i didn't want to pull out this card, but i'll have to.
> 
> stop being a woman. what does a woman do? she says "body doesn't matter" yet she wants the boy to be atleast 1.8 m tall. what i mean by that is if you're fine with that name, then stop wasting others (and yours) time.

I don't think that name changes proposed are a waste of time and we are leaving a register as to why we use this names.
Personally I wouldn't change the names, why do you want to change them @lokka30 ? Did I miss a message?

**Comment by yannicklamprecht** [comment]
It's clearly a ServiceRegistry. Handler is meh, Manager is meh. `meh` alias it doesn't describe it's purpose.

**Comment by lokka30** [comment]
> It's clearly a ServiceRegistry. Handler is meh, Manager is meh. `meh` alias it doesn't describe it's purpose.

Best one so far.

**Comment by lokka30** [comment]
> > no. you're not handling services, are you? you're providing them, hence ServiceProvider.
> 
> The terminology `provider` and `consumer` is already used in the 'provider and consumer' model we describe Treasury integrations by. There is ought to be a better term we can use.
> 
> I still think `Handler` is alright, because "the class **handles** the registration of services".

@MrNemo64 this is why I wanted to change it :)

**Comment by MrIvanPlays** [comment]
Ok you win. Change it to ServiceRegistry

**Comment by lokka30** [comment]
'Rename `ServiceProvider` to `ServiceRegistry`'

Yes:
* @yannicklamprecht 
* @Jikoo 
* @lokka30 

Unclear:
* @MrNemo64

No:
* @MrIvanPlays 

***

I will work on the change now.

**Comment by MrNemo64** [comment]
I'm down for the change

**Comment by lokka30** [comment]
note: see #154.
