### ISSUE TITLE
Do pre-release testing

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#15]
Before `v1.0` is released to Spigot, it must be tested. The following checklist will be edited as testing proceeds.

**Currently this issue is on hold since the plugin is not ready for testing - it is still in development.**

- [x] Test startup and shutdown (no errors?)
- [x] Test the update checker (ensure to force-enable it in the code, use a different resource ID since Treasury doesn't have one yet)
- [x] Test the `settings.yml` file (toggle the update checker, see if that functions)
- [x] Test `/treasury` (base command)
- [x] Test `/treasury help`
- [x] Test `/treasury info`
- [x] Test `/treasury reload`
- [x] Test `/treasury migrate <providerFrom> <providerTo>` but without any economy providers installed, just to make sure the command runs somewhat properly.
- [x] Test the `messages.yml` file (change some subcommand messages, see if that functions)

The API is highly likely to work, and it is currently too difficult to test, so any bugs found after release will be promptly resolved.

**Comment by MrIvanPlays** [comment]
#45 with its abstracted code tested:

 - [x] Test startup and shutdown
 - [x] Test `/treasury`
 - [x] Test `/treasury help`
 - [x] Test `/treasury info`
 - [x] Test `/treasury reload`

**Comment by lokka30** [comment]
> 
> 
> #45 with its abstracted code tested:
> 
>     * [x]  Test startup and shutdown
> 
>     * [x]  Test `/treasury`
> 
>     * [x]  Test `/treasury help`
> 
>     * [x]  Test `/treasury info`
> 
>     * [x]  Test `/treasury reload`

Woot! I haven't actually launched the plugin before, glad it's working brilliantly. Thanks for testing those.

**Comment by MrIvanPlays** [comment]
It's working brilliantly on #45 's implementation. Not sure about master branch's implementation :)

**Comment by lokka30** [comment]
The testing procedure is now different than what it was more than 2 months ago. I'll revise the strategy once we've reached the testing stage.

**Comment by lokka30** [comment]
The only thing left is to test `/treasury migrate` once two economy providers are available. Otherwise, all done. Closing this issue since such is not possible yet.
