### ISSUE TITLE
Use `Event` interface

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#150]
Instead of using the `Object` type for events, I think all events should implement an empty `Event` interface.

**Comment by MrIvanPlays** [comment]
My ears are all open for hearing your very good reason of why we should.

**Comment by lokka30** [comment]
> My ears are all open for hearing your very good reason of why we should.

What's wrong with enforcing an explicit statement that a class is an event? I haven't heard any reasons we shouldn't.

> The coolest thing about our events is that you can make literally every object an event. What do I mean by that is that you don't need to extend any voodoo magic classes. You just create your object and call it and you're good to go.

This is exactly it. Why should an object that was **never** intended to be an event, become such?

A class can simply implement `Event`, an empty interface that just declares it is intention. Zero extending of any voodoo magic classes.

I'm not going to die on this hill but I am trying to do what's best for the long-term rigidity of our code. The last thing I want is for a headache to happen and anyone says 'Told you so'.
