### ISSUE TITLE
Add PlaceholderAPI placeholders for the Economy API

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#156]

**Comment by MrIvanPlays** [comment]
????????

**Comment by MrNemo64** [comment]
What placeholders does an economy api need?

**Comment by lokka30** [comment]
Vault currently has the following PAPI placeholders:

```
%vault_eco_balance%
%vault_eco_balance_commas%
%vault_eco_balance_fixed%
%vault_eco_balance_formatted%
%vault_eco_top_balance_#%
%vault_eco_top_balance_fixed_#%
%vault_eco_top_balance_formatted_#%
%vault_eco_top_balance_commas_#%
%vault_eco_top_player_#%
%vault_eco_top_rank%
```

Permissions

```
%vault_rank%
%vault_rank_capital%
%vault_ranks%
%vault_ranks_capital%
%vault_prefix%
%vault_rankprefix%
%vault_rankprefix_#%
%vault_suffix%
%vault_ranksuffix%
%vault_ranksuffix_#%
%vault_prefix_color%
```

Hope this was useful @MrNemo64 @MrIvanPlays

**Comment by MrIvanPlays** [comment]
that's an easy one to implement.

**Comment by MrNemo64** [comment]
> that's an easy one to implement.

What are you thinking about? A method in the Economy provider like `replacePlaceholders`? Or just an implementation of PAPI on the plugin module?

**Comment by MrIvanPlays** [comment]
> > that's an easy one to implement.
> 
> What are you thinking about? A method in the Economy provider like `replacePlaceholders`? Or just an implementation of PAPI on the plugin module?

why should we make the provider plugin to do that when treasury plugin can do it? implementation of PAPI in plugin-bukkit module

**Comment by lokka30** [comment]
yup the Treasury plugin will handle everything. I'll have to look at how PAPI gets the 'baltop' from Vault because Treasury nor Vault have those methods built-in (and I don't have any plan on changing that).
