### ISSUE TITLE
Typo in the Update

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#157]
### Expected behavior

Added default method implementation for `Account#setName` for PlayerAccounts ([@MrIvanPlays](https://www.spigotmc.org/members/209496/))

### Observed behavior

Added default[/code] method implementation for [icode]Account#setNam for PlayerAccounts ([@MrIvanPlays](https://www.spigotmc.org/members/209496/))

### Reproduction steps

https://www.spigotmc.org/resources/treasury.99531/updates

### Treasury information

```shell
None
```

**Comment by lokka30** [comment]
Thanks :)
