### ISSUE TITLE
Allow blank issues (no template / form)

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#169]
It is inconvenient to make issues now as from a maintainer’s standpoint because we are forced to follow a template/form. Such is unnecessary when I am not filing a bug report or the user’s context is needed.
A simple Boolean can be changed which makes blank issues allowed on our issue tracker. I can survive without it but what’s the point in keeping it this way?
If people abuse the blank issue, close it and ask them to make their issue properly.

**Comment by MrIvanPlays** [comment]
problem is that if there is such option nobody would follow the template. against

**Comment by MrNemo64** [comment]
Instead of a black issue we could have a "simple issue" template that is easily filled

**Comment by Jikoo** [comment]
As a maintainer you can bypass the form: https://github.com/lokka30/Treasury/issues/new
Against.

**Comment by lokka30** [comment]
Cheers Jikoo, I'll bookmark that. Wish GH made that more accessible.
