### ISSUE TITLE
Improve .gitignore

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#17]
The .gitifnore file is an important part of a git repository, how ever the .gitignore of this repository doesn't cover all files. Since it only contemplates Intell Idea, contributors using other ides will have trouble. I propouse using a more extense file, there are good generators online that can do the work, for example, [this ](https://www.toptal.com/developers/gitignore/api/eclipse,intellij,maven,java,intellij+all,intellij+iml)would be a .gitignore template for Intell Idea, Eclipse, Java and Maven

**Comment by Geolykt** [comment]
Eclipse user here - you should ALWAYS take a look at what you are staging before you commit, no matter your gitignore file.

**Comment by lokka30** [comment]
Cheers for opening this issue - I'll commit a fix to this very soon. I've seen your PR although I've decided not to use the template directly, instead I've copied the file names that I think are relevant.
