### ISSUE TITLE
Non-functional PAPI placeholders

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#172]
All [PAPI placeholders for Treasury](https://github.com/lokka30/Treasury/pull/158#issuecomment-1044100099) apart from the ones to view a specific player's balance seem to be non-funtional. The `{precision}dp` one also seems to be non-functional.

It's possibly something on BetterEconomy's end.

**Comment by MrIvanPlays** [comment]
`{precision}dp` has to do with BetterEconomy and it is nothing to do on our end.

> apart the ones to view a specific player's balance
could you be more specific? I've tested all the placeholders I listed on the comment you linked and they work as intended for me.

**Comment by lokka30** [comment]
> `{precision}dp` has to do with BetterEconomy and it is nothing to do on our end.
> 
> > apart the ones to view a specific player's balance
> 
> could you be more specific? I've tested all the placeholders I listed on the comment you linked and they work as intended for me.

Sweet! Since you've tested all of those placeholders, don't worry about this issue - it's highly likely a BetterEconomy issue. Even if we later find that the placeholders are actually non-functional, then that's fine because we can promptly patch it as it's not API.
I'll prepare the changelog now, and then we'll be ready for release 🎊

**Comment by MrIvanPlays** [comment]
in order for the baltop placeholders to work you have to enable a config function present in PAPI's config if that's what doesn't work for you @lokka30

**Comment by lokka30** [comment]
> in order for the baltop placeholders to work you have to enable a config function present in PAPI's config if that's what doesn't work for you @lokka30

ah, okay, that solves that then. I'll make sure to note that in the wiki
