### ISSUE TITLE
Document PAPI placeholders

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#174]
See conversation in #172 - need to document the linked list of placeholders and also need to document how to enable baltop on PAPI's end.

**Comment by MrIvanPlays** [comment]
treasury's placeholderapi hook settings are in placeholderapi's config.yml - in order to enable baltop you have to enable this as shown
![image](https://user-images.githubusercontent.com/37958105/160778074-6e8e9d2e-e104-4e36-ae08-8587da0dbdcb.png)

**Comment by lokka30** [comment]
Done.
