### ISSUE TITLE
Typo in update release

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#175]
### Expected behavior

Added missing `@NotNull` annotation ([@Esophose](https://www.spigotmc.org/members/34168/))

### Observed behavior

Added missing `[USER=1035723]@NotNull[/USER]` annotation ([@Esophose](https://www.spigotmc.org/members/34168/))

### Reproduction steps

Go to https://www.spigotmc.org/resources/treasury.99531/update?update=450938

### Treasury information

```shell
None
```

**Comment by lokka30** [comment]
Thank you! This was even reported by another user and I edited it, but looks like I have to actually leave a space between the `@` and `NotNull` 😦

**Comment by MrNemo64** [comment]
Have you tryed putting an `\` before the @?
