### ISSUE TITLE
Want to turn off Discord mobile verification

### ISSUE THREAD

**Issue by inrhor** [lokka30/Treasury#186]
### Expected behavior

![uTools_1655648202302](https://user-images.githubusercontent.com/67991284/174485594-523aba78-54c0-48e9-a6a0-a7f6a8a21a49.png)
I have recently developed an economy plugin, and I can't discuss it. I mainly have doubts about the "EconomySubscriber<Account> subscription" issue, I don't know its function, and my translation understanding is limited.

### Observed behavior

1

### Reproduction steps

1

### Treasury information

```shell
no
```

**Comment by lokka30** [comment]
Hi, what is your Discord tag? I'll give you the bypass role and we can discuss there. :)
