### ISSUE TITLE
Set/reset balance operations should use a new transaction type `SET`

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#198]
### User Story

Suggested by `Hai_tun#8468` and myself on the [ArcanePlugins Discord Server](https://www.discord.io/arcaneplugins).

### Describe the solution you'd like.

Instead of set/resets not being a transaction, they should be a transaction of a new Type named `SET`.

### Describe alternatives you've considered.

Keeping them as current: not transactions.

**Comment by MrNemo64** [comment]
If we want transactions to be a history of teh activity we kinda need them

**Comment by lokka30** [comment]
In this case a reset would also be classified as a `SET`, since it is really just a `SET` with the amount automatically declared. @MrIvanPlays
