### ISSUE TITLE
Add Transaction objects (for usage in a Transaction History)

### ISSUE THREAD

**Issue by Articdive** [lokka30/Treasury#2]

**Comment by lokka30** [comment]
Excellent idea. This will definitely be added. Thank you for the suggestion.

**Comment by Articdive** [comment]
Could also serve as a great way to send the Database something that "definitely did happen", The Database then knows to definitely write whatever that Transaction says.

**Comment by lokka30** [comment]
Added the Transaction class, and I believe I've finished all of the Transaction events code as well.
[See commit](https://github.com/lokka30/Treasury/commit/f45cd1aba09f1534923943963ca993ae18fb5f6f)
If this does not satisfy your intention please re-open. :)
