### ISSUE TITLE
EconomyProvider Registry not being Detected

### ISSUE THREAD

**Issue by GamerCoder215** [lokka30/Treasury#209]
### Expected behavior

EconomyProvider is registered correctly and viewed

### Observed behavior

Linked to [Issue #33 on Novaconomy](https://github.com/Team-Inceptus/Novaconomy/issues/33):
> @GamerCoder215 I tried to start it up with plugmanX not installed and no change still cannot use commands I took a look in the latest log but I do not see any specific errors I will also note that treasury does not register novaconomy as an economy with this issue as well [latest.log](https://github.com/Team-Inceptus/Novaconomy/files/9737696/latest.log) ![image](https://user-images.githubusercontent.com/70445191/194669505-c595af91-de78-4dd0-ac76-6abb76cf3ccd.png)

### Reproduction steps

1. Load Novaconomy Plugin with Treasury Installed
2. Novaconomy recognizes Treasury installed, uses Treasury API to register its EconomyProvider
3. Treasury should work as usual, however no EconomyProvider is shown.

![image](https://user-images.githubusercontent.com/54124162/194670263-e8061c5d-7a5c-44c5-86f6-682286e895c5.png)

### Stack trace or error log

```shell
https://gist.github.com/GamerCoder215/48345f47695e259c3403241d7d80bf18
```

### Treasury information

```shell
Unknown
```

### Additional information

Code Used:
```java
// TreasuryRegistry implements EconomyProvider
    public TreasuryRegistry(Novaconomy plugin) {
        // this.plugin = plugin;

        ConfigurationSerialization.registerClass(TreasuryAccount.class);
        TreasuryAccount.global = NovaConfig.getGlobalStorage();
        TreasuryAccount.treasuryAccounts = TreasuryAccount.global.isConfigurationSection(TREASURY_ACCOUNTS) ? TreasuryAccount.global.getConfigurationSection(TREASURY_ACCOUNTS) : TreasuryAccount.global.createSection(TREASURY_ACCOUNTS);

        ServiceRegistry r = ServiceRegistry.INSTANCE;
        if (!r.serviceFor(EconomyProvider.class).isPresent()) {
            r.registerService(EconomyProvider.class, this, plugin.getName(), ServicePriority.HIGH);
            plugin.getLogger().info("Injected Novaconomy EconomyProvider into Treasury");
        }
    }
```

More code is available on the [Novaconomy Repository](https://github.com/Team-Inceptus/Novaconomy/blob/master/plugin/src/main/java/us/teaminceptus/novaconomy/treasury/TreasuryRegistry.java).

**Comment by GamerCoder215** [comment]
Update:
Treasury is crossing out the Novaconomy EconomyProvider.
![image](https://user-images.githubusercontent.com/70445191/194675704-de040029-9405-49a8-8f2a-30ea8e6f585d.png)

**Comment by lokka30** [comment]
The crossing out is a visual bug on server consoles where the strikethrough on the arrow seems to continue forwards 😃 

I also recommend registering the economy provider regardless if one is present or not - this is why we are using priorities.

Is the issue resolved?

**Comment by GamerCoder215** [comment]
> The crossing out is a visual bug on server consoles where the strikethrough on the arrow seems to continue forwards 😃
> 
> I also recommend registering the economy provider regardless if one is present or not - this is why we are using priorities.
> 
> Is the issue resolved?

I usually check that to make sure I don't register it multiple times (unless that's automatically checked)

His response was:
> okay update i figured out why treasury crossed out novaconomy I had treasury (as well on the servers) in bungee but novaconomy only on one server, which wasnt needed so you dont need to look into that

I'll close this as nothing related to Treasury needs further investigation, thanks for the information though.
