### ISSUE TITLE
Fix JavaDoc formatting

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#27]
Currently the Javadoc format follows a pattern: author - see - since - description - parameters - throws - return
This format creates the problem that JavaDoc genertors think that the description is part of the see tag, we can see this by generating the javadoc.
![Image of generated JavaDoc](https://i.imgur.com/0xPQV9I.png)
Another problem with it is using formatting options that don't exists in the JavaDoc like \`Marked` This JavaDoc was generated using the java 8 jdk

**Comment by lokka30** [comment]
> 
> 
> Currently the Javadoc format follows a pattern: author - see - since - description - parameters - throws - return This format creates the problem that JavaDoc genertors think that the description is part of the see tag, we can see this by generating the javadoc. ![Image of generated JavaDoc](https://camo.githubusercontent.com/56bf1609991210a7ac52a7119edaae39493f01e1ad15c84e99f01456c5532def/68747470733a2f2f692e696d6775722e636f6d2f307850515639492e706e67) Another problem with it is using formatting options that don't exists in the JavaDoc like `Marked` This JavaDoc was generated using the java 8 jdk

Thanks for bringing this to my attention. I'll for sure fix the javadoc formatting throughout the resource.

However, the `Marked` formatting is intentional - even if they are not formatted in the JavaDoc I still find these characters useful to highlight a specific part of texts i.e. class names.

( This issue is linked to #4. )

**Comment by Geolykt** [comment]
In this case, use `{@link ClassName}`

**Comment by lokka30** [comment]
> 
> 
> Currently the Javadoc format follows a pattern: author - see - since - description - parameters - throws - return This format creates the problem that JavaDoc genertors think that the description is part of the see tag, we can see this by generating the javadoc. ![Image of generated JavaDoc](https://camo.githubusercontent.com/56bf1609991210a7ac52a7119edaae39493f01e1ad15c84e99f01456c5532def/68747470733a2f2f692e696d6775722e636f6d2f307850515639492e706e67) Another problem with it is using formatting options that don't exists in the JavaDoc like `Marked` This JavaDoc was generated using the java 8 jdk

To solve this issue, do my comments go above all of the Javadoc tags?

**Comment by MrNemo64** [comment]
Since we now have a EconomyAPIVersion enum maybe the \@since tag could have a link to the enum entry corresponding to the version. So for example for something added in v1.0.0
```Java
/**
 * ...
 * @since {@link me.lokka30.treasury.api.economy.misc.EconomyAPIVersion#VERSION_1 v1.0.0}
 */
```
So we have a link to that enum entry and the text is still v1.0.0
I also think that the enum entryes should be renamed. Instead of `VERSION_1` it could be `v1_0_0_0`. I think I'll create a new issue to address some things that I would change of the EconomyAPIVersion

**Comment by lokka30** [comment]
> 
> 
> Since we now have a EconomyAPIVersion enum, maybe the `@since` tag could have a link to the enum entry corresponding to the version. So, for example, for something added in v1.0.0:
> 
> ```java
> /**
>  * ...
>  * @since {@link me.lokka30.treasury.api.economy.misc.EconomyAPIVersion#VERSION_1 v1.0.0}
>  */
> ```
> 
> So we have a link to that enum entry and the text is still v1.0.0.
> 
> I also think that the enum entries should be renamed. See #46.

The link is quite bulky - perhaps just a text version of the API version would be better?

`@since API v1.0.0 | PLUGIN v1.0.0`

**Comment by Geolykt** [comment]
Why would we want to sperate API and plugin version?

**Comment by Jikoo** [comment]
> The link is quite bulky - perhaps just a text version of the API version would be better?
> 
> `@since API v1.0.0 | PLUGIN v1.0.0`

While I'm overall ambivalent to link/non-link status, including the plugin version doesn't make sense because the API should not be aware of implementation details.

**Comment by MrNemo64** [comment]
> > Since we now have a EconomyAPIVersion enum, maybe the `@since` tag could have a link to the enum entry corresponding to the version. So, for example, for something added in v1.0.0:
> > ```java
> > /**
> >  * ...
> >  * @since {@link me.lokka30.treasury.api.economy.misc.EconomyAPIVersion#VERSION_1 v1.0.0}
> >  */
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So we have a link to that enum entry and the text is still v1.0.0.
> > I also think that the enum entries should be renamed. See #46.
> 
> The link is quite bulky - perhaps just a text version of the API version would be better?
> 
> `@since API v1.0.0 | PLUGIN v1.0.0`

The link is long because we class name is also long but in the documentation it would still appear as "v1.0.0" and not "me.lokka30.treasury.api.economy.misc.EconomyAPIVersion#VERSION_1"



> > The link is quite bulky - perhaps just a text version of the API version would be better?
> > `@since API v1.0.0 | PLUGIN v1.0.0`
> 
> While I'm overall ambivalent to link/non-link status, including the plugin version doesn't make sense because the API should not be aware of implementation details.
> 
> /e Unless that was a regex or and not just an inline pipe, plugin side docs. That makes sense, yeah. Definitely plaintext plugin side.

I agree with that. The API should not contain any type of information about the plugin or the implementations

**Comment by lokka30** [comment]
> Why would we want to sperate API and plugin version?
The API version is independent of the plugin version as changes can be made to the API but not the plugin and vice versa.

> While I'm overall ambivalent to link/non-link status, including the plugin version doesn't make sense because the API should not be aware of implementation details.
> /e Unless that was a regex or and not just an inline pipe, plugin side docs. That makes sense, yeah. Definitely plaintext plugin side.

> I agree with that. The API should not contain any type of information about the plugin or the implementations. About linking the enum, it's just an idea not much really changes by adding it or not

Do you suggest that we only include 'api' or 'plugin' depending on which module the code is in?

> Link is formatted without the classpath

Brilliant - let's keep it this way.

**Comment by MrNemo64** [comment]
> Do you suggest that we only include 'api' or 'plugin' depending on which module the code is in?

Yes. The api is just that, a collection of interfaces that specify how interactions are made. If we also mention the plugin in the api module it gets confusing because you also have to think about the plugin while coding, even though you don't need to. 
And what of someone implements the api but not to make a provider or use the services of the provider but to create it's own plugin? 

If we also mention the plugin on the api module people can get confused because maybe the things that you said about the plugin aren't even true (they are running another plugin instead of treasury)

**Comment by lokka30** [comment]
Merging this issue with #4
