### ISSUE TITLE
Last thoughts on Treasury v2's API? YOUR OPINION is wanted!

### ISSUE THREAD

**Issue by MrIvanPlays** [lokka30/Treasury#279]
If you have any comments on the 2.0.0 API and stuff you'd like changed, please state your opinion here.

As for the meantime:
![image](https://github.com/ArcanePlugins/Treasury/assets/37958105/59b1f70a-f82e-4e01-aae7-18e1c5d514a1)

**Comment by lokka30** [comment]
Hi @Jikoo, @MrNemo64, @yannicklamprecht, @creatorfromhell, and @Geolykt, 
Just tagging you in case you wanted to add any comments as we are about to wrap up all code changes for Treasury v2's API and would prefer to not make any breaking changes for the distant future.

**Comment by MrNemo64** [comment]
> Hi @Jikoo, @MrNemo64, @yannicklamprecht, @creatorfromhell, and @Geolykt, Just tagging you in case you wanted to add any comments as we are about to wrap up all code changes for Treasury v2's API and would prefer to not make any breaking changes for the distant future.

To be honest, university has been consuming all my time for quite some months now so I'm not up to date with the api, I don't know what changed and such. I've looked arround a bit on `dev/2.0.0` and I've seen things like the AccountAccessor which I really like. I don't really know what changed, but I like what I saw.
Good job to whoever has been doing all of this

**Comment by lokka30** [comment]
Best of luck with your studies, I've been dealing with the same lately (and will be for another ~2 years). Ivan's kindly done a ton of development heavy lifting for us. Thanks for your thoughts!

**Comment by Jikoo** [comment]
I think I've been moderately good about staying abreast of things and reviewing most PRs, though I haven't done much else. I'm also (back) in the university boat for a career transition, life's been a bit hectic. Big shoutout to Ivan for carrying us to this release!

**Comment by lokka30** [comment]
Best of luck to you as well Jikoo :)

**Comment by yannicklamprecht** [comment]
The only thing I found was that NonPlayer and Plugin with the namespaced key will be equal. Should it be that way?
Rest of the API I looked into, is way better than before.

**Comment by lokka30** [comment]
> The only thing I found was that NonPlayer and Plugin with the namespaced key will be equal. Should it be that way? Rest of the API I looked into, is way better than before.

Awesome to hear, thanks for your feedback! Please could you elaborate on the NamespacedKey part - not quite sure what you mean here?

**Comment by MrIvanPlays** [comment]
I see. I think we should also do a class check in the equals inside Cause.NonPlayer and Cause.Plugin

**Comment by yannicklamprecht** [comment]
> I see. I think we should also do a class check in the equals inside Cause.NonPlayer and Cause.Plugin

You do but afterwards just checking the key twice. Just remove the second if statement.

**Comment by lokka30** [comment]
I've been discussing with Ivan on Discord about replacing the NamespacedKey for `Cause.Plugin` with just a String
