### ISSUE TITLE
Set up Maven profiles to publish to various repositories

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#28]
See discussion [here](https://www.spigotmc.org/threads/new-economy-api-looking-for-your-feedback.527805/page-3#post-4280306).

**Comment by lokka30** [comment]
I think I'll use JitPack and CodeMC - although I would prefer to use CodeMC, they go offline far too often, JitPack far less so. Developers can pick whichever they prefer :)

**Comment by MrIvanPlays** [comment]
I'm ready to provide you with access to ci.mrivanplays.com (respectively repo.mrivanplays.com).
![machine uptime](https://img.mrivanplays.com/qgyrezobvr.png)
I can probably create a javadocs subdomain to host not only yours but mine's.  

It's getting down once every 1-2 months for updates which take ~30 minutes.

**Comment by lokka30** [comment]
Is it difficult to integrate multiple CI systems at once in IntelliJ?

I'm using JitPack manually for my other plugins but I would love to make it automated. Especially if it can publish to different CI systems in one or few clicks.

**Comment by MrIvanPlays** [comment]
> Is it difficult to integrate multiple CI systems at once in IntelliJ?

wdym? I can create you an account on ci.mrivanplays.com and add this github repository to trigger a build once it finds a new commit, which in fact will deploy it to repo.mrivanplays.com (if you don't want it deployed to `ivan-<releases/snapshots>`, i can create a new nexus repository with another name, say `public-<releases/snapshots>`). This github repo will only need some minor adjustments for deploying and generating javadocs. 
unfortunately I dont know to set up the deployment repositories in maven as you want to deploy to codemc too. I think we can discuss that with gabriele and find a solution. The best is to go with one of the 2 - either me or codemc.
I don't know about jitpack tho... it has been problematic for me, the reason why I went self hosting. I don't even know why you want to deploy to jitpack...

**Comment by MrIvanPlays** [comment]
Ok about javadocs; I've set up a simple folder index: https://jd.mrivanplays.com/

I will create a command on the server which is going to move generated javadocs from jenkins to the location where this subdomain is hosted.

**Comment by lokka30** [comment]
I've never had any problems with JitPack. I've read that people experience problems with JitPack when doing complicated builds, which Treasury's is far from. I don't know why people are against it, I am not biased towards it, I just don't see any solid evidence against using it.

CodeMC is great - except for its uptime. There have been a handful of cases where CodeMC went down whilst I was developing my plugins, which is why I don't want to rely on it.

I am happy to support 2 or 3 official CI repositories so long all of them can be automated with GitHub commits and/or releases. If one server goes down, then there are 2 official alternatives to use.

Please let me know if you think there any flaws in my thinking here - I'm only aiming for the best.

**Comment by MrIvanPlays** [comment]
With a quick google search I found out that maven's profiles are capable of changing the deploy nexus repository e.g

```maven
<profiles>
  <profile>
    <id>deployTomrivan</id>
    <!-- plugins needed and etc to deploy to repo.mrivanplays.com -->
  </profile>
  <profile>
    <id>deployToCodeMC</id>
    <!-- plugins needed and etc to deploy to repo.codemc.io -->+
  </profile>
</profiles>
```

and the CI which is gonna run the build for the plugin is gonna either do `mvn deploy -P deployTomrivan` or `mvn deploy -P deployToCodeMC`. 

I am able to assist with setting up stuff both for my instances and codemc. But we should first wait on #37 . There are stuff I need to discuss with you @lokka30 in private so you can send me a friend request in discord.

**Comment by MrNemo64** [comment]
Have you considered using github packages?
https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

**Comment by MrIvanPlays** [comment]
github packages isn't as widespread and it is hard to use (for me), also you don't have
javadocs hosting.

**Comment by MrNemo64** [comment]
The main benefit of github packages is that the repo is always avilable and whenever we publish a release it automatically updates the repo. For the docs we can use github pages, other options avilable

**Comment by MrIvanPlays** [comment]
> The main benefit of github packages is that the repo is always avilable and whenever we publish a release it automatically updates the repo. For the docs we can use github pages, other options avilable

Sure but github packages are hard both for developers and users. I have instances of people asking how to download from github. The best is to stick with the current "standard" or what people have been used to: jenkins for downloading builds, a nexus repository manager for API deployment and retrieval from developers.

**Comment by Geolykt** [comment]
OSSRH might also be a good option over jitpack and CodeMC once API and plattform is seperated given that it is more or less THE place to host maven artifacts. Of course it isn't as good as proper CI but at least it is good enough for release builds

**Comment by MrIvanPlays** [comment]
> OSSRH might also be a good option over jitpack and CodeMC

OSSRH is the maven central repository. While it is the best solution for deploying and distributing the API to projects, it is risky to upload anything to it that has to do with bukkit on maven central because it can get taken down due to the DMCA from 7 years ago. 

Also that it can't be really automated because it requires the files to be signed using gpg, and also at peak hours you may need to wait a bunch of time until you can upload your thing. 

Yea, I had such an [experience...](https://search.maven.org/search?q=com.github.mrivanplays) if you think I didn't.

**Comment by lokka30** [comment]
> 
> 
> Have you considered using github packages? https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

I have, but it's more difficult to use as extra user configuration is required. I don't see an issue in offering it but I don't know why anyone would use it over the other repositories which are far easier to use.

**Comment by lokka30** [comment]
I have decided to change from a multi-repository system to a single-repository system. To avoid people seeing this issue and its older comments, I have decided to close this and replace it with #57 .
