### ISSUE TITLE
Strip colours out of logging

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#286]
I'd like to have all colours stripped out of logging as it seems a few Minecraft updates ago (somewhere around 1.18 or 1.19?) Paper recommended against logging with colours.

Actions to resolve:

- Strip colour formatting out of all log messages sent by Treasury. (note: coloured messages are achieved using legacy formatting codes such as `&f`)

**Comment by MrIvanPlays** [comment]
Already done for paper. I've implemented the ComponentLogger which supports colors, if there isn't a ComponentLogger implementation it won't log with colors.
