### ISSUE TITLE
New Author

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#294]
I quote my announcement on Discord for context,

<blockquote>
Hi everyone,

Due to a variety of reasons, I've decided to step away from Minecraft development for the most part. Life moves on - for quite a while I've lost most of the time and motivation I had (and required) to work on my projects.

LevelledMobs 3 onwards has almost solely been developed by penalbuffalo, so little changes with Penal being appointed as the new author.
All other projects will remain as-is until a new author is appointed for each respective project.

Thank you to penalbuffalo and ultimaoath for working hard on LevelledMobs for the community.
Thank you to mrivanplays and Jikoo for your hard work on Treasury.
Thank you to the community for adopting and supporting my peers, my projects, and myself.

I'll still be around to contribute where I can, though I no longer have the capacity to maintain my projects.

I've required SpigotMC staff to transfer the LevelledMobs resource to Penal so he can manage the resource there as well.

Cheers :)
Lachlan.
</blockquote>

I no longer have the time or motivation to continue continue maintaining Treasury, so I wish to transfer authorship to someone else. If you would like to be the new author of Treasury, please post below.

I will still be present as an administrator of the project, and am happy to aid in resolving disputes and providing direction. I am no longer able to continue contributing to the project as per normal.

Regards

**Comment by lokka30** [comment]
@MrIvanPlays and @Jikoo - are either of you interested in becoming the project's new author? Otherwise, I can search for someone else to take over.

**Comment by Jikoo** [comment]
I unfortunately also don't have the time to head the project - always happy to do what I can and review work, but life's already kept me from contributing where I had hoped to, let alone tackling a bigger role. I imagine this is you formalizing a state similar to mine, and I hope you succeed in your other endeavors.

**Comment by lokka30** [comment]
> I unfortunately also don't have the time to head the project - always happy to do what I can and review work, but life's already kept me from contributing where I had hoped to, let alone tackling a bigger role. I imagine this is you formalizing a state similar to mine, and I hope you succeed in your other endeavors.

Thanks Jikoo, same with you; unfortunately I don't have time to maintain the project to the degree you currently are as well. I'll contribute when I can though I shouldn't be considered a maintainer at this stage.

**Comment by MrIvanPlays** [comment]
I can take over

**Comment by lokka30** [comment]
No problems, thanks @MrIvanPlays. To take over authorship you will need to be able to maintain the SpigotMC resource page as well, is this possible?

**Comment by MrIvanPlays** [comment]
Yes

**Comment by lokka30** [comment]
Fantastic, requesting Spigot staff to transfer resource now.
Thank you very much Ivan.
