### ISSUE TITLE
Removing MultiWorld support

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#30]
See discussion [here](https://www.spigotmc.org/threads/new-economy-api-looking-for-your-feedback.527805/page-3#post-4280306).

**Comment by MrNemo64** [comment]
> On more thought, per-world balances are somewhat useless - if users want per-world balances, they can add currencies that are only used in certain worlds. If all the shops in RewardLand only accept NeatWorldDosh your CoolWorldBucks are useless there despite being visible and available. It offloads the strain of multi-world management from the API/implementation onto the server owner configuring the setup. They can make it as complex or as simple as their needs without any extra effort on the programmers' ends.

[Quote here](https://www.spigotmc.org/threads/new-economy-api-looking-for-your-feedback.527805/page-3#post-4280726), I think this is a good idea. I gave it the 'Agree'

**Comment by lokka30** [comment]
Cheers. I'll move forward with this.

**Comment by lokka30** [comment]
Done.
