### ISSUE TITLE
Add Transaction History

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#33]
@MrNemo64 suggested the following method: `public Collection<BankTransactionEntry> getTransactionHistory() { ... }`

Will expand on this issue later. If anyone has thoughts on this issue please drop them below :)

**Comment by MrNemo64** [comment]
While working on #31 I realized that depending on the structure of the BankTransaction we may have to change some things. If, for example, the BankTransaction holds a player and the amount that they withdraw/deposit then the `withdrawBalance` and `depositBalance` from the Account interface may also need to have an `UUID player` param so we can register who withdraws/deposits. There are some other methods that may need to change but these 2 are the first ones that come to my mind

**Comment by lokka30** [comment]
> While working on #31 I realized that depending on the structure of the BankTransaction we may have to change some things. If, for example, the BankTransaction holds a player and the amount that they withdraw/deposit then the `withdrawBalance` and `depositBalance` from the Account interface may also need to have an `UUID player` param so we can register who withdraws/deposits. There are some other methods that may need to change but these 2 are the first ones that come to my mind

What if there is no player involved in the transaction?
For multiple players involved I think separate transactions would be fine.
