### ISSUE TITLE
Minecraft Version & Java Version Requirements

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#39]
There have been a few ideas going around of improving Treasury through means which are inaccessible to Treasury's current minimum requirements of Java 8 and Minecraft 1.7.

The following is my opinion of course, please comment below if you would like me to amend this in any way.

I'm interested in hearing what you all think.

# Changing the minimum Minecraft version

I'll call these Minecraft versions 'major': 1.7, 1.8, 1.12, 1.16, 1.17 - they are used by lots of people relative to the other versions.

## 1.7
* 🔴 1.7 is very old (2013!) - difficult to support
* 🔴 Requires a little tinkering to work with newer Java versions
* 🔴 Almost all of these servers run Java 8
* 🟢 We don't loose potential users from back this far

## 1.16
* 🟢 1.16 is recent (2020) - easy to support
* 🟢 Works out of the box with the latest Java versions
* 🔴 A handful of 1.16 servers still run Java 8
* 🟢 Almost all of our potential users are in this margin

## 1.17
* 🟢 Latest version as of writing this (2021) - easy to support
* 🟢 Works out of the box with the latest Java versions
* 🟢 All servers run Java 16+
* 🔴 We still have most of our potential users in this margin, but we loose a noticeable chunk by removing 1.16 support

# Changing the minimum Java version

## 8
* 🟢 LTS version, easy to obtain
* 🟢 We don't lose any users
* 🟢 Works with all server versions out of the box
* 🔴 We can't use any of the shiny newer Java features
* 🟢 Every server runs at least this version

## 11
* 🟢 LTS version, easy to obtain
* 🔴 We lose the Java 8+ users
* 🔴 May require tinkering to get working with older servers
* 🟢 We gain almost all of the new Java features we are interested in
* 🔴 Was never a required version by Mojang

## 16
* 🔴 Non-LTS version, more difficult to obtain
* 🔴 We lose the Java 8+ users
* 🔴 Requires tinkering to get working with older servers
* 🟢 We gain all of the new Java features we are interested in
* 🟢 Required for 1.17+ servers

## 17
* 🟢 LTS version, easy to obtain
* 🔴 We lose the Java 8+ users
* 🔴 Requires tinkering to get working with older servers
* 🟢 We gain all of the new Java features we are interested in
* 🔴 Was never a required version by Mojang

**Comment by MrIvanPlays** [comment]
1.18 is going to use java 17.

**Comment by lokka30** [comment]
> 
> 
> 1.18 is going to use java 17.

I'm so glad that Mojang is finally forcing people to update their Java.

**Comment by yannicklamprecht** [comment]
> > 1.18 is going to use java 17.
> 
> I'm so glad that Mojang is finally forcing people to update their Java. I hope they continue this trend with each new Java release, or at least, every new LTS release.
 Hopefully they follow the bi yearly cycle. No need to stay on LTS.

**Comment by MrNemo64** [comment]
> > > 1.18 is going to use java 17.
> > 
> > 
> > I'm so glad that Mojang is finally forcing people to update their Java. I hope they continue this trend with each new Java release, or at least, every new LTS release.
> 
> Hopefully they follow the bi yearly cycle. No need to stay on LTS.

I think updating is the right move. We can finally start to leave java 1.8 behind

**Comment by lokka30** [comment]
I believe we should stay with the following minimum requirements:
* Java 8
* MC 1.7

As much as I would like to make Treasury use Java 17, we need to consider that:
* All plugins using Treasury will need to also update to Java 17
* Server owners that run 1.7/1.8/1.12 will not be able to utilize Treasury. There might be a launch flag fix or something but this might not be viable for these server owners.

The Minecraft version here doesn't really matter because Treasury does not utilize any version-specific features other than what is present in the Bukkit API at the time. That's why we can comfortably support back to 1.7 without putting a burden on us.

I don't know what Java 17 will bring us other than `record` classes. We can live without it.

Down the line we can absolutely change the bar of which servers can run Treasury or not if we need to. But we should only be modifying this if it's necessary, not for minor programmer luxuries.
