### ISSUE TITLE
Split EconomyProvider interface or remove hasXSupport methods

### ISSUE THREAD

**Issue by Jikoo** [lokka30/Treasury#44]
Edit:
After the discussion here, I feel like the `hasXSupport` methods are a bad idea and I would actually like to see Treasury drop the idea of not implementing the entirety of its interfaces.

> It really doesn't make sense to me to have 50% of the methods be designed to not be implemented. Anyone who does offer Treasury support should be able to offer bank support with minimal extra work due to how similar the accounts are.

If we do truly want a method to check for support that should likely just be rolled into the API version system, not the provider interface(s). The javadocs for each method state the API version it was added in and the provider states the API version it was programmed against.

Original writeup:
I would like to see `EconomyProvider` separated into several interfaces.

As a developer, it makes it a lot easier to work with player/bank accounts if I know exactly what is available to me rather than constantly re-checking if banks are supported and whatnot.

As a server owner, the increased granularity makes it possible to invent a solution that more exactly suits my needs by selecting the exact bank and player account implementations I want.

* `TreasuryApiProvider`
  * Provide Treasury API version implemented, owning plugin
* ~~`CurrencyProvider extends TreasuryApiProvider`~~
  * ~~Provides currency definitions and handles parsing~~
  * ~~Should define currency management (creation, deletion, modification, etc.)~~
  * ~~Treasury should probably implement and provide at `ServicePriority.Lowest`~~
    * See #40
  * Definitely needs improvement, but outside the scope of this issue
* `AccountProvider extends TreasuryApiProvider`
  * Provides a `requestCurrenciesInUse` or similar method
    * Allows `CurrencyProvider` to support undefined currencies, making migration easier.
* `PlayerAccountProvider extends AccountProvider`
  * Provides `PlayerAccounts`
* `BankAccountProvider extends AccountProvider`
  * Provides `BankAccounts`
  * Methods should not clash with `PlayerAccountProvider`
    * Makes it possible to create a generic `MyEconomyImpl implements PlayerAccountProvider, BankAccountProvider` to mimic Vault style interface usage

**Comment by MrIvanPlays** [comment]
I mean we can clean it up after these calls. Its just an idea I am not forcing it to go into the implementation.

**Comment by Jikoo** [comment]
I've edited OP to reflect my current stance on this for clarity.

> An idea I've just got in my mind. Whenever a economy provider tries to register into treasury, make a test of all features. If it fails at any feature, do not register it.

I don't hate it, but what do we do about things like a misconfigured SQL connection? Generally those plugins may reconnect on a custom reload command, but if we've unregistered their economy they may not realize they need to re-register it. It may be more trouble than it's worth.

Re: unnecessary calls to the provider: A couple queries to test functionality would be a drop in the bucket compared to regular player usage. I don't think a single account creation (and then ideally deletion - probably should add deletion API) and maybe a balance modification would break the server's back.

**Comment by Geolykt** [comment]
> Re: unnecessary calls to the provider: A couple queries to test functionality would be a drop in the bucket compared to regular player usage. I don't think a single account creation (and then ideally deletion - probably should add deletion API) and maybe a balance modification would break the server's back.

Should this ever be done it should be important that the accounts are deleted after the tests as otherwise functionalities such as baltop or a global balance view would be broken

**Comment by MrIvanPlays** [comment]
> I don't hate it, but what do we do about things like a misconfigured SQL connection?

We can force the provider to call a method with an input whether it is ready for a feature test or not. If it doesn't call it after x amount of time, throw an exception.

**Comment by lokka30** [comment]
What do you all think about implementing #43 to solve this issue? @Jikoo @MrIvanPlays @Geolykt @MrNemo64

**Comment by MrIvanPlays** [comment]
It would be better to have it as an enum instead of splitting the economyprovider since it would be more difficult for implementing.

**Comment by MrNemo64** [comment]
> What do you all think about implementing #43 to solve this issue? @Jikoo @MrIvanPlays @Geolykt @MrNemo64 

I like the idea. Would like to develop the idea in that issue.


About splitting the provider into several providers, could we have all providers splited as described by Jikoo or something like that and then have the economy provider extend all those interfaces? 
This way if you want to use the separated parts them you just cast, if you want all use the EconomyProvider. This would allow also for the implementation to have its logic separated _by default_

**Comment by Jikoo** [comment]
> What do you all think about implementing #43 to solve this issue?

Overall this would be closed by any decision on it, ignoring, a removal, a split of the interfaces, or a refactor to a new location.

Personally would prefer to see Treasury drop the idea of not supporting methods and not split the interface - banks are so similar to regular accounts that if you support one you may as well do both.

Having an inbuilt "is method available in version" method could be handy, but hopefully the dependent plugin would just check API version and warn instead (or Treasury could handle it if API version required > current version). I feel like the API version system where version is easily accessible by implementations should be sufficient instead of adding additional back and forth of feature checks.

**Comment by lokka30** [comment]
> > What do you all think about implementing #43 to solve this issue?
> 
> Overall this would be closed by any decision on it, ignoring, a removal, a split of the interfaces, or a refactor to a new location.
> 
> Personally would prefer to see Treasury drop the idea of not supporting methods and not split the interface - banks are so similar to regular accounts that if you support one you may as well do both.
> 
> Having an inbuilt "is method available in version" method could be handy, but hopefully the dependent plugin would just check API version and warn instead (or Treasury could handle it if API version required > current version). I feel like the API version system where version is easily accessible by implementations should be sufficient instead of adding additional back and forth of feature checks.

I agree that a majority of Treasury's features should not be optional anymore, especially bank accounts. Although I am still concerned that there could be things added into the API that are considered 'optional' for plugins to implement. How would we manage this? Go with the 'has ... support enum' route? Best of both worlds I think.

**Comment by lokka30** [comment]
Merging this issue into #43.
