### ISSUE TITLE
Set up CodeMC repository

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#57]
- [x] submit request to CodeMC Discord `(at 21st Dec 2021)`
- [x] receive response to request from CodeMC director **(accepted!)**
- [ ] set up auto-deployment scripts
- [ ] test

# Instructions

## Add these settings to pom.xml

```xml
<distributionManagement>
    <repository>
        <id>codemc-releases</id>
        <url>https://repo.codemc.io/repository/maven-releases/</url>
    </repository>
    <snapshotRepository>
        <id>codemc-snapshots</id>
        <url>https://repo.codemc.io/repository/maven-snapshots/</url>
    </snapshotRepository>
</distributionManagement>
```

## Add commit status

Follow instructions [here](https://docs.codemc.io/jenkins/github-integration/#add-commitstatus).

## Automatically build

Follow the instructions [here](https://docs.codemc.io/jenkins/github-integration/#automatically-build).

## Create Maven job

Follow the instructions [here](https://docs.codemc.io/jenkins/maven/#creating-a-maven-job).

## Deploy to the CodeMC Nexus

Follow the instructions [here](https://docs.codemc.io/jenkins/deploy/).

**Comment by lokka30** [comment]
It is unlikely that CodeMC will be used as the repository for Treasury's builds as they have not responded to anyone's messages to request access since October 8th. We don't have months of time to spare, I don't want the choice of CI server to delay us.

Please leave your opinion on what CI to use [here](https://www.spigotmc.org/threads/upcoming-economy-api-were-interested-in-your-feedback.527805/page-6). My current aim is to ask if Ivan will be able to kindly host Treasury's builds, but I want to make sure people are okay with it.

**Comment by portlek** [comment]
we can use github actions which is really simple for publishing releases.

**Comment by MrIvanPlays** [comment]
> we can use maven central and github actions which is really simple to use and publish.

Sure but we also need a maven repository and javadocs host. Ci.mrivanplays.com offers such: repo.mrivanplays.com and jd.mrivanplays.com . Deploying code which uses bukkit to maven central is risky due to the DMCA.

**Comment by portlek** [comment]
you can publish sources and javadocs too, there is no risk for dmca btw if you know what you are doing. i published almost 25 artifacts and i have never see an issue.

**Comment by portlek** [comment]
my thought is there is no need for external hosts for publishing artifacts or other CI stuffs. there are many features in github for these things.

**Comment by portlek** [comment]
i use to publish my artifacts `https://oss.sonatype.org/` they are going from here to `https://repo1.maven.org/maven2/` you just don't need to any external host or something like that.

**Comment by MrIvanPlays** [comment]
What I meant for javadocs is not from viewing source in the ide but from a site in a more friendly manner. 

You're deploying to maven central. Maven central can have a lot of traffic at some times and deploying might fail. Also that you need to gpgsign your artifacts. 

Maven central shall not be used for automatic deployment.

**Comment by portlek** [comment]
we can use github-pages for javadocs.
i have never seen a problem with maven central for about 2 years when i do auto deployment. it's free and fast enough. i think you should check it once and you will see how easy it is. also gpgsign is a thing you have to do yes but it's also really easy to implement for maven/gradle. just a simple 2-3 lines of code.

**Comment by MrIvanPlays** [comment]
I have used maven central and I know what it is to gpgsign and wait for traffic to go down to deploy artifacts. Search for com.github.mrivanplays and you will see strange stuff. 

Maven central is not a solution. Neither is jitpack.

**Comment by portlek** [comment]
maven central is a solution. all of the world is using it. why because it's a good solution for almost everything. i don't know why you don't want to use it, is it because you just don't want to wait 10~ minutes for release :D anyways go ahead.

**Comment by MrIvanPlays** [comment]
Thing is automatic deployment. With maven central due to the aforementioned reasons it can't be really done. You need to be very lucky to get something deployed automatically at peak hours.

**Comment by portlek** [comment]
you can see my 70~ artifacts which published via github actions a.k.a. automatic deployment. you don't need to be really lucky to publish perfectly actually but, yes you have to be really lucky to see these problems. because i didn't see much problem with maven central when i publish all of my artifacts. maybe you saw a lot of problems when you publish your artifacts but for me i guess i saw 2 or 3 problems for staging/releasing but, i did 70 artifacts and they have 10~ versions for each which means 700~ artifacts published successfully and i'm doing these publishing everyday.

also if the problem you don't want to see when you publishing is that slowing down the releasing, you can also experience when you use external hosting :D i think this is not an argument for not using maven central. yes it downs sometimes although it's rare but, your dedicated/vds/vps machine also can down due to hosting problems :D i don't understand what the argument is to not choice the maven central to publish.

**Comment by MrIvanPlays** [comment]
My argument is that at peak hours you may not be able to deploy no matter whether you're doing this automatically or by yourself.

**Comment by MrNemo64** [comment]
Is there any way we can schedule the deployment so it's not done instantly? I don't really think releasing 3 or 4 hours latter will matter that much and maven central doesn't require you to add a repository

**Comment by portlek** [comment]
@MrNemo64 yes you can. you can do everything with github actions.

**Comment by lokka30** [comment]
I've messaged Gabriel, he may look into the requests within a few days time.

**Comment by lokka30** [comment]
I have updated this issue to reflect our current usage, not what was from 2 weeks ago.

**Comment by MrIvanPlays** [comment]
https://ci.mrivanplays.com/job/Treasury/
https://repo.mrivanplays.com/service/rest/repository/browse/od-snapshots/me/lokka30/
https://jd.mrivanplays.com/treasury-api/overview-summary.html
https://jd.mrivanplays.com/treasury-api-bukkit/

**Comment by MrIvanPlays** [comment]
Do we really need github actions? I'm not really familiar with it. If we _really_ need it, I'd like for someone else to make it so that it builds on every commit and releases whenever we bump the version to a release version (if that's possible).

**Comment by MrNemo64** [comment]
> https://ci.mrivanplays.com/job/Treasury/ https://repo.mrivanplays.com/service/rest/repository/browse/od-snapshots/me/lokka30/ https://jd.mrivanplays.com/treasury-api/overview-summary.html https://jd.mrivanplays.com/treasury-api-bukkit/

What java version did you use to generate the docs? Seems like java 8 but the generator has been improved in newer versions generating more usable docs

**Comment by MrIvanPlays** [comment]
> > java 8 because that is the version that it was decided treasury's minimum supported version.
> 
> That makes sense but I do think that using the latest version would heavily benefit the docs

the priority is support as much as possible so we're as much as possible concurrent to vault. docs are of acceptable quality.

**Comment by MrNemo64** [comment]
> > > java 8 because that is the version that it was decided treasury's minimum supported version.
> > 
> > 
> > That makes sense but I do think that using the latest version would heavily benefit the docs
> 
> the priority is support as much as possible so we're as much as possible concurrent to vault. javadocs are of acceptable quality.

It doesn't have the search bar, searching for a method/class that you don't event know if it exists is much easyer with the search bar. isn't there a way to keep on using java 8 but have the latest version of javadoc?

**Comment by MrIvanPlays** [comment]
> > > > java 8 because that is the version that it was decided treasury's minimum supported version.
> > > 
> > > 
> > > That makes sense but I do think that using the latest version would heavily benefit the docs
> > 
> > 
> > the priority is support as much as possible so we're as much as possible concurrent to vault. javadocs are of acceptable quality.
> 
> It doesn't have the search bar, searching for a method/class that you don't event know if it exists is much easyer with the search bar. isn't there a way to keep on using java 8 but have the latest version of javadoc?

No. Try to find the reason yourself. If you really can't poke me and I'll tell ya.

**Comment by MrIvanPlays** [comment]
now we have a github pages link for the javadocs: https://lokka30.github.io/Treasury/javadocs

**Comment by MrIvanPlays** [comment]
we're not going to wait for approval on codemc in order to release 1.0.0

**Comment by lokka30** [comment]
absolutely not. good call on removing the 1.0 assignment

**Comment by MrIvanPlays** [comment]
Done - https://ci.codemc.io/job/lokka30/job/Treasury/
