### ISSUE TITLE
Remove bank owners, use just members instead

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#58]
@MrNemo64, what do you think about this idea? I believe there should only be bank members, but of course each bank member can have different permissions.

**Comment by MrNemo64** [comment]
I think it makes more sense to first think about _what exactly_ are we describing by bank memeber and owner, at least I don't have it clear

**Comment by lokka30** [comment]
> I think it makes more sense to first think about _what exactly_ are we describing by bank memeber and owner, at least I don't have it clear

The thing is - a bank member can currently be given all the permissions, couldn't that be considered a bank owner?

**Comment by MrNemo64** [comment]
I suppose it would still be useful to be able to get all players with all the permissions, or have a method that given some permissions returns all the players that have them

**Comment by lokka30** [comment]
We could do that

**Comment by MrNemo64** [comment]
And a bank member would be a player with at least one permision of the bank right? Or am I mistaken?

**Comment by lokka30** [comment]
> And a bank member would be a player with at least one permision of the bank right? Or am I mistaken?

it's up to the economy provider if there can be members with no permissions but that wouldn't make sense IMO

**Comment by MrNemo64** [comment]
Then we could remove the owner methods and just have the members ones and one to get players with X permissions.
If we really wanted owners we could just add an 'OWNER' permission
I think this idea is worth commenting on spigot before anything though.
