### ISSUE TITLE
Edit Spigot Page

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#65]
The Spigot page is outdated at the moment. I want to edit it to make it more accurate and concise.

***

G'day Spigot Community,

## Treasury
Treasury is a multi-platform library plugin that offers APIs which offer a central place for provider and consumer plugins to interact with each other.

We define provider plugins as those which offer a service to the server, such as, your Permissions plugin (e.g. LuckPerms), your Economy plugin (e.g. Essentials), your Chat plugin (e.g. VentureChat) and so on.

We are currently focused on completing our greatest feature - the Treasury Economy API - before we expand into offering Permission, Chat and Land Protection APIs. This allows us to streamline development and release Treasury earlier. The Treasury Economy API is attempting to be an upgrade to Vault's Economy API, which is in dire need of such upgrades. 

Since we are in pre-release stage, we are very interested in *your* feedback. This is because Treasury can receive major modifications in this stage without causing any issues due to breaking compatibility. Therefore, if you have any comments, suggestions, contributions, criticisms and so on, please let us know. Now is the perfect time for it to happen. We are very welcoming to contributions too, let us know if you are interested in giving us a hand. 😉 

This post will receive updates to ensure the information here is accurate. Please note that the comments in the first few pages may no longer be valid as Treasury has undergone multiple significant changes during its development.

@Jikoo, @MrIvanPlays and myself are maintaining Treasury. There are also a handful of [contributors](https://github.com/lokka30/Treasury/wiki/Credits) such as @Nemo_64 and @Geolykt who have kindly reviewed and/or modified Treasury's code for improvement.

## Quick Links
Here are a few links which you may find useful.

* [View the source code](https://github.com/lokka30/Treasury)
* [View the to-do list](https://github.com/lokka30/Treasury/issues?q=is%3Aopen+is%3Aissue+project%3Alokka30%2FTreasury%2F1) (using the search filter `is:open is:issue project:lokka30/Treasury/1`)
* [View the wiki](https://github.com/lokka30/Treasury/wiki) (work in progress)

### Multi-Platform Compatibility
We aim to make Treasury run on different server software. Treasury can currently run on Bukkit servers (CraftBukkit, Spigot, Paper, etc), although we aim to expand into offering compatibility with Sponge, Bungee, Velocity and so on.
This is achieved through using Maven modules and platform-independent classes in the APIs.

### Improved Concurrency
If you're using Vault with an economy plugin that needs to query a database, your server will freeze whilst it waits for the request to arrive. With Treasury, we use a specialized interface, the [EconomySubscriber](https://github.com/lokka30/Treasury/blob/master/api/src/main/java/me/lokka30/treasury/api/economy/response/EconomySubscriber.java), to significantly decrease the potential for a plugin to lock the main thread with an API call.

### Multi-Currency
Treasury makes it very simple to create multiple currencies and convert between them. There are is also a utility to parse money amounts (e.g. `$2500` as a command argument). The Currency class also contains other information and utilities such as its character (e.g. `$`) and an amount formatter (e.g. `5.2513516` -> `5 dollars and 25 cents`)

### UUIDs
Treasury's Economy API utilizes UUIDs instead of player names or the OfflinePlayer class. This provides advantages such as platform independence, name change support, no pointless Mojang profile lookups (which lock the main thread), and being (realistically) impossible for ID duplication to occur, for better stability.

### Player Accounts
Each player is entitled to their own player account, where they can have balances in multiple different currencies, e.g. Notch has 5 VoteTokens and $200 billion dollars.

### Bank Accounts
Like player accounts, bank accounts can have balances in multiple different currencies. However, bank accounts are not owned by any sole entity, rather, they can be controlled by *bank members*.

Bank accounts can have zero or more bank members within it, each bank member has their own set of Bank Permissions allocated to manage what they are allowed to do with the bank account. For example, Jeff could only have the `CONSULT` permission so he can view the bank account's balance, but Jane has all of the bank permissions so she can deposit, withdraw, etc.

Note that Treasury does not take any control over bank transactions and member permissions, it only makes these features available to the economy provider, which instead can choose to utilize this system.

Bank accounts are very useful for land protection plugins like Factions and Towny as bank accounts can store a pool of money.

### Transactions
Transactions can store information about a specific transaction, e.g. md_5 deposits $50 in his account from reaching a new playtime goal.

Treasury offers Transaction Events which can be optionally made available by the economy provider. If utilized, this allows plugins to spy on transactions and cancel them from happening at their choice. Currently, Transaction Events are only available for the Bukkit implementation of Treasury, but we aim to support other platforms which also have events.

## 'What about Vault'?
To avoid bloating this post with the answer, please view the [Comparison Wiki page](https://github.com/lokka30/Treasury/wiki/Comparison-to-other-APIs) where I explain my own comparison of Treasury against Vault. :)
If you have any comments about this comparison please reply below.

## What plugins will Treasury be available in on launch?
Let me know if you want your plugin listed here! :)

* [TownyAdvanced](https://www.spigotmc.org/resources/towny-advanced.72694/) by `@LlmDl` (Economy Consumer)
* [ElementalEconomy](https://github.com/lokka30/ElementalEconomy) by `@lokka30` (Economy Provider)
* [EasyConomyAdvanced](https://github.com/Geolykt/EasyConomyAdvanced) by `@Geol` (Economy Provider)
* [EconomyPlus](https://www.spigotmc.org/resources/economyplus.92975/) by `@_ItsWagPvP` (Economy Provider)

Note: I have no clue who will use Treasury, developers can choose themselves. This list only includes the authors of plugins who have seen this post *and* use some sort of economy in their plugin *and* are interested in adding Treasury to their resource. So, of course this list will be smaller than the actual outcome.

## What license is used?
The [MIT License](https://github.com/lokka30/Treasury/blob/master/LICENSE.md), which is a very popular choice for open source software like Treasury, bringing many freedoms to those who wish to utilize the resource.

# Conclusion

We hope that you are interested in utilizing Treasury some day. We have tried to keep this post concise, so it may be missing information you are looking for - please do not be afraid to reply to this thread if you have any questions or comments.

***

Please propose any changes to this page below. Still work-in-progress.

Tagging users who may be interested: @MrNemo64 @MrIvanPlays @Jikoo

**Comment by lokka30** [comment]
Edit: using smaller headings now.

**Comment by MrIvanPlays** [comment]
I will like it however you come up with it. You have the ability to make stuff look and sound cool so I agree.

**Comment by lokka30** [comment]
Currently I'm braindead on what content to put into the `Major Features` section. That's pretty much all that's left to do. If you have any ideas please let me know 👍🏻

**Comment by MrNemo64** [comment]
> Since we are in pre-release stage, we are very interested in _your_ feedback. If you would be willing to let us know about any opinions, suggestions and criticisms you have of Treasury, please do so. We are also very welcoming to contributions.

I'd mention that since we haven't released yet we are able to make mayor changes to the API



> Currently I'm braindead on what content to put into the `Major Features` section. That's pretty much all that's left to do. If you have any ideas please let me know 👍🏻

You can mention the transactions and that bank accounts have permissions, being able to switch economy providers at runtime. I don't think vault has these features

**Comment by MrIvanPlays** [comment]
I agree on mentioning until a pre release has came out we are able to break the API however we want.

**Comment by lokka30** [comment]
Thanks for the suggestions. I've edited the features section quite significantly now. I'll take a look at the code and see what else I might be missing.

**Comment by MrNemo64** [comment]
> Note that Treasury is currently in development, major changes to the API which happen almost daily

This section sounds wired to me

```
Note that Treasury is still under development, this means that we are able to make mayor changes to the api without any kind of problem. If you see something that you think it should change/could be improved, now it's the time to say it (_winky emoji_?)
```

**Comment by MrIvanPlays** [comment]
@MrNemo64 its major not mayor.

**Comment by lokka30** [comment]
Thanks, edited that part.

**Comment by lokka30** [comment]
I'll forward this change to the actual Spigot page tomorrow. We can always make edits thereafter too. I will also reply to the thread to let people know that the project has been silently going full steam ahead. I am very interested in having more people on board especially for code and feature review. I also want to talk to various developers to see if they are interested in adopting it, once Treasury's Economy API is in a near-complete state.

**Comment by MrNemo64** [comment]
> @MrNemo64 its major not mayor

True, my main language is Spanish. Normally I realise when I randomly switch between languages but sometimes I miss a word xd

**Comment by lokka30** [comment]
Spigot page updated.
