### ISSUE TITLE
Add method to get all accounts a player is member of/has X permission on

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#67]
Right now if I want to get all the accounts a player has, for example, `withdraw` permission on then I have to go thruough all accounts and check, not really optimal. The `EconomyProvider` could have a 
`void retriveAllAccountsPlayerIsMemberOf(UUID player, EconomySubscriber<Collection<? extends Acount>>)`
`void retriveAllAccountsIdPlayerIsMemberOf(UUID player, EconomySubscriber<Collection<UUID>>)`
`void retriveAllAccountsPlayerHasPermission(UUID player, BankAccountPermission[] permissions, EconomySubscriber<Collection<? extends BankAccount>>)`
`void retriveAllAccountsIdPlayerHasPermission(UUID player, BankAccountPermission[] permissions, EconomySubscriber<Collection<UUID>>)`

**Comment by lokka30** [comment]
To simplify it, should we only have the `Id` methods?

**Comment by MrNemo64** [comment]
> To simplify it, should we only have the `Id` methods?

I thought about it but since there is no way (that i know) to request several accounts at the same time, having to request them one by one in a loop and all that could be tedious. I really don't mind what we end up having as long as you can get them

**Comment by MrIvanPlays** [comment]
thinking abt it, internally, an economy provider would do the same as you described:

> Right now if I want to get all the accounts a player has, for example, `withdraw` permission on then I have to go ~~thruough~~ through all accounts and check

so in my opinion this is really a "I don't want to do this in my plugin which utilizes Treasury for economy stuff, lets pass it to the economy provider" thing.

**Comment by MrNemo64** [comment]
> thinking abt it, internally, an economy provider would do the same as you described:
> 
> > Right now if I want to get all the accounts a player has, for example, `withdraw` permission on then I have to go ~thruough~ through all accounts and check
> 
> so in my opinion this is really a "I don't want to do this in my plugin which utilizes Treasury for economy stuff, lets pass it to the economy provider" thing.

I hadn't thought of it that way. My thinking was:
> If I want to get all the accounts a player can deposit money on, I would need to get all the bank account ids with `retrieveBankAccountIds`, then I need to use `retrieveBankAccount` to get the bank account. Then I can do `hasPermission` on the bank account, if this returns true then save somewhere the bank account, if not then do nothing with it. At the end I get all my bank accounts just as I want but I make the economy provider have to give me all the bank account instances and for most of them I will just use the `hasPermission` method, why make so many requests and maybe make the provider have to load from the data base a bank account that I will probably not even use?

As you said, the provider can just do that, load all of them even if only the `hasPermission` method is going to be used on it but why force a provider to do it this way? Some providers may directly check the database to see if the player has the permissions and only load those.

We can try to this methods default, this way we don't force the provider to implemet them but if they don't want this unnecessary amount of request they can modify it.

**Comment by MrIvanPlays** [comment]
actually haven't thought that an economy provider can have a table bound for permissions and query just the permissions. yet the proposed solution about the isMemberOf situation wouldn't be different at all compared to what you'd normally do. 

still, the average developer won't consider using multiple tables so "they don't make the database dirty" and would dump all the data in 1 table, which would mean that the average economy plugin would probably do the same things as you described to implement these methods.

**Comment by lokka30** [comment]
I agree with exactly this.

> We can try to this methods default, this way we don't force the provider to implement them but if they don't want this unnecessary amount of request they can modify it.

We can supply a default method which, although sends a lot of queries, achieves the method's intention without any work on the economy provider's developer's part being required.

**Comment by MrNemo64** [comment]
> I agree with exactly this.
> 
> > We can try to this methods default, this way we don't force the provider to implement them but if they don't want this unnecessary amount of request they can modify it.
> 
> We can supply a default method which, although sends a lot of queries, achieves the method's intention without any work on the economy provider's developer's part being required.

I'll try to do it soon. Since we just started the week I'm a little bussy

**Comment by MrIvanPlays** [comment]
> > I agree with exactly this.
> > > We can try to this methods default, this way we don't force the provider to implement them but if they don't want this unnecessary amount of request they can modify it.
> > 
> > 
> > We can supply a default method which, although sends a lot of queries, achieves the method's intention without any work on the economy provider's developer's part being required.
> 
> I'll try to do it soon. Since we just started the week I'm a little bussy

I can finish your PR. Do you agree?

**Comment by MrNemo64** [comment]
> > > I agree with exactly this.
> > > > We can try to this methods default, this way we don't force the provider to implement them but if they don't want this unnecessary amount of request they can modify it.
> > > 
> > > 
> > > We can supply a default method which, although sends a lot of queries, achieves the method's intention without any work on the economy provider's developer's part being required.
> > 
> > 
> > I'll try to do it soon. Since we just started the week I'm a little bussy
> 
> I can finish your PR. Do you agree?

I don't really mind. Best case scenario I can do it today, worst case scenario we have to wait untill Friday. If you have time and want to finish it go on
