### ISSUE TITLE
Add bank account names

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#70]
I've had this idea for quite some time now and I can't figure out if it's worth it to add to the API. My thought process what that with code we diferenciate accounts by their uuid, in game there is an easy diferenciation between player and bank accounts but what about diferenciating several bank accounts? If a player owns 2 diferent bank accounts, how is he supposed to diferenciate them? I don't thing the uuid will be usefull for them. So I thought of adding a `String name` field to bank accounts, so you can diferenciate them ingame but it feels like it should be left for any plugin that needs a name for a bank account, this however brings its problems.
I don't want to bloat the API with unecessary features and I don't think this is really necessary but it has been on my mind for quite some time so I just wrote it.

Just to clarify, if we add this there should be no api provided way of getting bank accounts by the name.

To give an example: My plugin wants to charge X coins on a player and I show in chat/open a menu with all the accounts that they can withdraw from. The player could just select the account based on the income but what if they want to withdraw from an especific account? Do that have to keep track of the coins in that account to identify it?
Seems like this is a my plugin problem and I should be the one to solve it, but if we have 2+ plugins that doing this then having a unique name for every bank account avoids the pain for the player of naming all bank accounts several times and unnecessary repetition of data between plugins

I want to hear your thoughts on this

**Comment by lokka30** [comment]
I believe the economy provider should handle mapping bank UUIDs to names.

**Comment by MrIvanPlays** [comment]
I agree bank accounts should have name, just like irl banks have names.
A command of a provider could look like `/withdraw <bankname> <currency> <amount>`

**Comment by lokka30** [comment]
Actually, I see a benefit in having bank names accessible through Treasury now.

**Comment by MrIvanPlays** [comment]
@Jikoo do you agree?

**Comment by Jikoo** [comment]
This seems like a good idea. Command-based implementations will be a lot more user-friendly if they can specify by name.
