### ISSUE TITLE
Rework failure reasons

### ISSUE THREAD

**Issue by lokka30** [lokka30/Treasury#73]
We need to add various failure reasons to the enum.
Feel free to suggest any below and I can add them in once #71 is merged.

Current approved list of additional constants:
```java
DATABASE_ERROR
```

**Comment by MrNemo64** [comment]
Instead of `SQL_ERROR` it should be `DATABASE_ERROR` as a provider may decide to use a no-sql database

**Comment by MrIvanPlays** [comment]
instead of having a enum with fail reasons, convert the enum to a final class or an interface (like the EconomyTransactionInitiator) which holds a message and some other type of data.
