### ISSUE TITLE
Currency System Overhaul

### ISSUE THREAD

**Issue by creatorfromhell** [lokka30/Treasury#74]
The currency system as it stands is very restrictive towards economy plugins who generally have their own currency system in place. While it is very nicely designed, it's designed as a system that should be inside an economy plugin itself and not inside of an API.

In general, the currency API oversteps what an API should provide.

Oversteps:
- Forcing the currency manager inside Treasury onto economy plugins
- Forcing the conversion standards inside Treasury onto economy plugins.
   - This really should just be a method that .to(Currency other) that is implemented by economy plugins
- Forcing currency UUIDs that are used nowhere inside the API onto economy plugins.  
- Forcing a default formatting system onto economy plugins.
- Forcing the currency registration system onto economy plugins.

As I stated before, in general the system is great, but it is a system that shouldn't be inside an API, but rather an economy plugin that implements the API.

Why is this a bad thing?
  The reason overstepping is a bad thing is it reduces the likelihood of adoption.

**Comment by MrNemo64** [comment]
I agree with most points here but

> Forcing currency UUIDs that are used nowhere inside the API onto economy plugins.

Since the methods take the Currency instance itself and not the UUID we could tecnically remove them but how would a plugin request the instance of the currency?

> Forcing a default formatting system onto economy plugins.

We need to provide a formatting system for plugins to use, how else are they supposed to display a currency?

> Forcing the currency registration system onto economy plugins.

Now that you mention it, i don't know if its good or not to have it

**Comment by creatorfromhell** [comment]
> I agree with most points here but
> 
> > Forcing currency UUIDs that are used nowhere inside the API onto economy plugins.
> 
> Since the methods take the Currency instance itself and not the UUID we could tecnically remove them but how would a plugin request the instance of the currency?


They would still use a currency identifier, but the issue is that forcing an economy plugin to specify it to be a UUID is rather radical. A string identifier is suitable enough, which provides freedom to be an UUID or not.

> 
> > Forcing a default formatting system onto economy plugins.
> 
> We need to provide a formatting system for plugins to use, how else are they supposed to display a currency?

When I meant "forcing a formatting system" I meant that forcing them to utilize Locale, when most plugins don't even have a Locale-based translation system in them is pretty restrictive. Simply having a formatting method with an amount and precision suffices, It should be up to the implementation, in my opinion.

> 
> > Forcing the currency registration system onto economy plugins.
> 
> Now that you mention it, i don't know if its good or not to have it

It really should just be a method to register a currency, not a full-blown manager inside of an API.

**Comment by MrNemo64** [comment]
> > I agree with most points here but
> > > Forcing currency UUIDs that are used nowhere inside the API onto economy plugins.
> > 
> > 
> > Since the methods take the Currency instance itself and not the UUID we could tecnically remove them but how would a plugin request the instance of the currency?
> 
> They would still use a currency identifier, but the issue is that forcing an economy plugin to specify it to be a UUID is rather radical. A string identifier is suitable enough, which provides freedom to be an UUID or not.

I have mixed feelings on this

> > > Forcing a default formatting system onto economy plugins.
> > 
> > 
> > We need to provide a formatting system for plugins to use, how else are they supposed to display a currency?
> 
> When I meant "forcing a formatting system" I meant that forcing them to utilize Locale, when most plugins don't even have a Locale-based translation system in them is pretty restrictive. Simply having a formatting method with an amount and precision suffices, It should be up to the implementation, in my opinion.

Agree on this

> > > Forcing the currency registration system onto economy plugins.
> > 
> > 
> > Now that you mention it, i don't know if its good or not to have it
> 
> It really should just be a method to register a currency, not a full-blown manager inside of an API.

Ideally an API should only contain interfaces and maybe POJOs so I agree with this

**Comment by creatorfromhell** [comment]
> > > I agree with most points here but
> > > > Forcing currency UUIDs that are used nowhere inside the API onto economy plugins.
> > > 
> > > 
> > > Since the methods take the Currency instance itself and not the UUID we could tecnically remove them but how would a plugin request the instance of the currency?
> > 
> > 
> > They would still use a currency identifier, but the issue is that forcing an economy plugin to specify it to be a UUID is rather radical. A string identifier is suitable enough, which provides freedom to be an UUID or not.
> 
> I have mixed feelings on this

I refer you to Essentials, where they have no currency system, just a singular name and a UUID-based system would never work.

**Comment by lokka30** [comment]
We don't need to worry about the money parsing since we can just supply a `default` interface method with the current code within it.
