### ISSUE TITLE
Fix some documentation and names

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#80]
In the description of this entry of FEATURE_NOT_SUPPORTED it is said
> It is paramount that plugins ensure that economy providers support certain methods (e.g. bank accounts) before attempting to access them.

yet NonPlayerAccounts are no longer an optional feature

In `Acount#setBalance` it is said
> Specified amounts must be AT OR ABOVE zero.

yet the provider may optionally support negative balances (`OptionalEconomyApiFeature#NEGATIVE_BALANCES`)

We have 2 packages for common clases between APIs: `me.lokka30.treasury.api.common` and `me.lokka30.treasury.api.misc`

There are most likely some more inconcistencies in the code/documentation but these are the ones that I had time to find. We should probably do a full scan of the code after the PR are closed to find these mistakes

EDIT: some more things I found
`EconomyFailureReason#ACCOUNT_DELETION_NOT_SUPPORTED` but account deletion is not an optional feature 
`EconomyFailureReason#ALREADY_MEMBER_OF_ACCOUNT` and `EconomyFailureReason#ALREADY_NOT_MEMBER_OF_ACCOUNT` but we no longer have an `addMember` method, members now are defined by permissions
`EconomyFailureReason#ALREADY_OWNER_OF_ACCOUNT` and `EconomyFailureReason#ALREADY_NOT_OWNER_OF_ACCOUNT` we no longer have owners

**Comment by lokka30** [comment]
Thanks for finding these
