### ISSUE TITLE
automation for releasing/verifying pull requests/updating dependencies/pr and issue templates.

### ISSUE THREAD

**Issue by portlek** [lokka30/Treasury#81]
- [x] Releasing wait for #57 
- [x] Verifying pull requests #84 
- [x] Updating dependencies #83 
  - [x] Need an issue label called `dependencies`
- [x] Issue templates #87 
- [x] P.R. templates

**Comment by lokka30** [comment]
Hi, thanks for the suggestion :)

Do you know of any specific Actions which can accomplish this?

I am unsure about automating releases. Perhaps semi-automation would be better for that.

**Comment by portlek** [comment]
you look at my github action fleet [here](https://github.com/Infumia/InfumiaLib/tree/master/.github/workflows)

**Comment by portlek** [comment]
it has not auto-release feature but it has auto-fill changelog feature for releases so, if any commit come to the master branch, release-drafter takes it and writes the draft-release's change log like that:
![image](https://user-images.githubusercontent.com/12835420/146928276-cbc78c3a-1210-4cbb-8d1f-eebfabc13931.png)
then you go to the edit page:
![image](https://user-images.githubusercontent.com/12835420/146928305-5b78daf2-5ca1-4e80-b973-f67d31d9a8cd.png)
click the publish release, that's it.
![image](https://user-images.githubusercontent.com/12835420/146928121-750de783-36e9-45db-b425-ba5929abc40a.png)

**Comment by MrIvanPlays** [comment]
we're not gonna use github releases. we're gonna use codemc.

either way it would be a good addition for something which updates dependencies.

**Comment by MrIvanPlays** [comment]
do we really need pull request templates?

**Comment by MrNemo64** [comment]
I think templates should be more for outsiders like server owners requesting features/finding bugs, we don't expected to know how the issues work so better to hide them with a template.
PR however, those are created by people that already know so they don't need guide

**Comment by lokka30** [comment]
The first checkbox is out of the scope of this issue (#57).
The last checkbox - PR templates - we've discussed is unnecessary.

Since all of the other checkboxes are completed, is this issue solved?

**Comment by lokka30** [comment]
Thank you very much 🎉
