### ISSUE TITLE
Typo in Comparison to other APIs wiki

### ISSUE THREAD

**Issue by MrNemo64** [lokka30/Treasury#99]
### Expected behavior

Treasury facilitates non-player accounts which are very similar to Vault's **bank accounts** although do not require owners or members

### Observed behavior

Treasury facilitates non-player accounts which are very similar to Vault's **ban kaccounts** although do not require owners or members

### Reproduction steps

Go to the comparison wiki page

### Treasury information

```shell
None
```

**Comment by lokka30** [comment]
Thank you
